### ISSUE TITLE
无法使用翻译功能

### ISSUE THREAD

**Issue by iamfugui** [koodo-reader/koodo-reader#1008]
### 我已经从 Github Release 安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10 及以下

### Koodo Reader 版本

1.5

### 我遇到的问题

无法使用翻译功能。网络是正常的，开启clash软件代理或关闭软件代理都显示错误。使用的是官网的1.5文档版，github上的1.6版本也试了还是不行，希望能看一下，不胜感激。

### 截图或录像(可选的)

<img width="779" alt="a" src="https://github.com/koodo-reader/koodo-reader/assets/61046396/9b7a34fc-19fb-400a-95c8-0e60bc21ac6f">
<img width="256" alt="b" src="https://github.com/koodo-reader/koodo-reader/assets/61046396/94bda4a6-04be-451c-b1a5-860ebb61c207">

### 图书文件(可选的)

[The Last Wish (Sapkowski Andrzej) (Z-Library).zip](https://github.com/koodo-reader/koodo-reader/files/13575911/The.Last.Wish.Sapkowski.Andrzej.Z-Library.zip)

**Comment by DingHanyang** [comment]
同样出现这个问题，请问你解决了吗？

**Comment by iamfugui** [comment]
> 同样出现这个问题，请问你解决了吗？

没有解决啊，作者摆烂了，都不想解决

**Comment by iamfugui** [comment]
直接关了，逆天
