### ISSUE TITLE
子目录对应错误

### ISSUE THREAD

**Issue by Alanclaude** [koodo-reader/koodo-reader#1012]
### 我已经从 Github Release 安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 11

### Koodo Reader 版本

1.6.0

## 目录对应错误
文件信息:
>文件目录内容例子:
>>1. 1卷
>>    1. 1.1章
>>    2. 1.2章
>>2. 2卷
>>    1. 2.1章
>>    2. 2.2章
>文件规范:
>Epub 3.0
 
现象:
1. 当点击"1.1章"时, 实际跳转的是"2.1章"
1. 如果点击"2.1章"那就会跳转到下一卷的"3.1章"
1. 如果下一卷没有对应章则会跳转到下一卷开头
1. 最后一卷点击后不会跳转任何地方, 而是不显示任何内容
1. 如果存在下一卷但是没有子目录的情况没有测试, 但是预测应该会与第3条的行为相同
2. 点击父目录可以正确跳转
3. 使用calibre打开一切正常

### 截图或录像(可选的)
![image](https://github.com/koodo-reader/koodo-reader/assets/77158950/097ab707-352a-4231-b0cb-1968605320f2)
![image](https://github.com/koodo-reader/koodo-reader/assets/77158950/d899b816-c237-4851-9fd4-1e1277d780db)
![image](https://github.com/koodo-reader/koodo-reader/assets/77158950/b91c19b9-d30e-4c84-ab14-418d6c227c2e)
![image](https://github.com/koodo-reader/koodo-reader/assets/77158950/ead8e95c-e5d6-41b4-9111-0facf63fbefa)
![image](https://github.com/koodo-reader/koodo-reader/assets/77158950/e919ca72-2bf7-4cb3-b002-e9129135e048)

**Comment by troyeguo** [comment]
麻烦提供一下电子书文件

**Comment by Alanclaude** [comment]
担心电子书直接上传github会有问题, 不清楚github邮件回复机制, 故先在邮件回复测试是否会公开, ***@***.***?&nbsp;


hhh
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年12月16日(星期六) 上午9:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [koodo-reader/koodo-reader] 子目录对应错误 (Issue #1012)





 
麻烦提供一下电子书文件

**Comment by Alanclaude** [comment]
&nbsp;------------------ 原始邮件 ------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年12月16日(星期六) 上午9:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [koodo-reader/koodo-reader] 子目录对应错误 (Issue #1012)





 
麻烦提供一下电子书文件

**Comment by Alanclaude** [comment]
[自制测试用 测试可以复现问题.zip](https://github.com/koodo-reader/koodo-reader/files/13691894/default.zip)

**Comment by troyeguo** [comment]
文件已收到，会在下个版本修复的
