### ISSUE TITLE
翻译出错

### ISSUE THREAD

**Issue by Tobeprmn** [koodo-reader/koodo-reader#1014]
### 我已经从 Github Release 安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10 及以下

### Koodo Reader 版本

1.6.0

### 我遇到的问题

在科学上网的前提下，使用koodo reader自带的翻译功能出错，翻译窗口显示空白，或显示“出错了”。
建议：是否可以增加翻译API功能，用户自己去相关翻译引擎网站申请API，然后接入koodo reader

### 截图或录像(可选的)

![1](https://github.com/koodo-reader/koodo-reader/assets/119318291/602f2aa8-5fac-482b-bf28-5a91cbda96f9)

**Comment by troyeguo** [comment]
国内请使用必应翻译
