### ISSUE TITLE
[Tracking] Ability to remove tracking

### ISSUE THREAD

**Issue by hacketiwack** [koodo-reader/koodo-reader#1027]
### I've searched the issue list, there is no similar features.

- [X] Yes

### If you have more than one feature, please open multiple issues to report respectively.

- [X] Yes

### Brief Introduction

In the source code, there is a link to Google Tag Manager.
What is this tracking used for? It must be removed if there are no good reason to have it.

### Details

The link: 
https://www.googletagmanager.com/gtag/js?id=G-LW49EYTQWY

**Comment by troyeguo** [comment]
Google analytics has been removed since version 1.5.2.
