### ISSUE TITLE
Support for variable fonts

### ISSUE THREAD

**Issue by planetkalpesh** [koodo-reader/koodo-reader#1052]
### I've searched the issue list, there is no similar features.

- [X] Yes

### If you have more than one feature, please open multiple issues to report respectively.

- [X] Yes

### Brief Introduction

I have installed variable fonts like Noto Sans downloaded from Google Fonts on my system. When I try to change the font from drop-down list it does'nt appear.

### Details

I think Koodo Reader does'nt support variable fonts. So if it does then can you add features to support it.

**Comment by troyeguo** [comment]
Works fine on my Win 10. This should be system-related problem.
![image](https://github.com/koodo-reader/koodo-reader/assets/13820674/e26ddfef-6c95-479e-8f1c-e0cd24a4f850)
