### ISSUE TITLE
Navigation issues

### ISSUE THREAD

**Issue by RAGNODIN** [koodo-reader/koodo-reader#1055]
### I've searched the issue list, there is no similar features.

- [X] Yes

### If you have more than one feature, please open multiple issues to report respectively.

- [X] Yes

### Brief Introduction

Okay so first of all I tried to check some underlined page links in one of those e pub books but it doesn't go to the link of that page.

### Details

So some of those inside linking of those pages books don't work, in addition to that going back or forward is not functional for example I can't directly go back to my actual reading point from another chapter by pressing back.
![Screenshot from 2024-01-23 18-06-29](https://github.com/koodo-reader/koodo-reader/assets/66489745/2bf338ed-ee5c-42bb-a4ed-754a513f770b)

**Comment by troyeguo** [comment]
Please contact us through email.
https://koodo.960960.xyz/en/support
