### ISSUE TITLE
Search Functionality Enhancement for Content-Based Queries

### ISSUE THREAD

**Issue by har5hcodes** [koodo-reader/koodo-reader#1059]
### I've searched the issue list, there is no similar features.

- [X] Yes

### If you have more than one feature, please open multiple issues to report respectively.

- [X] Yes

### Brief Introduction

Currently, the search feature allows users to find books by author names and titles. I propose expanding this to include searches based on the content within the books.

### Details

**Objective:** Enable users to search for books by specific text or content inside them, not just by title or author.
**Motivation:** Useful for readers who remember certain passages or quotes but not the book's title or author. It's especially beneficial for students and researchers.
**Implementation Suggestion:** Integrate a full-text search engine like Elasticsearch, index the content of each ebook, and provide a search interface for content queries.

**Comment by troyeguo** [comment]
This feature is basically not achievable. Search engine like Elasticsearch is not compatible with our tech stack.
