### ISSUE TITLE
提供取消阅读时选中文本后出现的菜单

### ISSUE THREAD

**Issue by TheLeastRemove** [koodo-reader/koodo-reader#1064]
### 我已经搜索了 Issue 列表，没有找到类似的需求

- [X] Yes

### 如果您有不止一个需求，请在多个 issue 里分别提交.

- [X] Yes

### 简单介绍

提供取消阅读时选中文本后出现的菜单，
![屏幕截图 2024-02-02 034549](https://github.com/koodo-reader/koodo-reader/assets/91277971/2a440191-f404-4ea8-8940-194e40a5f6ff)
这个菜单过于碍事，很糟糕的体验。

### 细节描述

提供一个选项，允许选中后不出现该菜单。或者可以调整菜单出现位置。

**Comment by troyeguo** [comment]
最新开发版已经支持
