### ISSUE TITLE
关于想到指定位置 about reach the specific page

### ISSUE THREAD

**Issue by jokerinkfc** [koodo-reader/koodo-reader#1065]
### 我已经搜索了 Issue 列表，没有找到类似的需求

- [X] Yes

### 如果您有不止一个需求，请在多个 issue 里分别提交.

- [X] Yes

### 简单介绍

目前好像缺失直接转到书本某一章节的某一页的功能，而软件显然是能识别一章节有多少页的，没有这个直接跳转到某一页的功能使用起来不够方便。希望作者可以加入这个功能。
Seems that the software lack the function to turn to the specific page, while the software obviously is able to recognize how many pages in one chapter.  Hope you can add the function in the future version. 

### 细节描述

目前好像缺失直接转到书本某一章节的某一页的功能，而软件显然是能识别一章节有多少页，没有这个直接跳转到某一页的功能使用起来不够方便。希望作者可以加入这个功能。比如想直接跳到某本书第二章节第100页，但由于只能选择章节，需要一页一页翻过去，十分麻烦。
Seems that the software lack the function to turn to the appointed page, while the software obviously is able to recognize how many pages in one chapter.  Hope you can add the function in the future version.

**Comment by troyeguo** [comment]
识别到页是渲染章节时做，页数需要根据图书窗口大小，字体大小等各种设置渲染完之后才能获取到，无法提前获取。
