### ISSUE TITLE
Emphasize the select button

### ISSUE THREAD

**Issue by angelicachao** [koodo-reader/koodo-reader#1070]
### I've searched the issue list, there is no similar features.

- [X] Yes

### If you have more than one feature, please open multiple issues to report respectively.

- [X] Yes

### Brief Introduction

Emphasize the select button by changing it's style?

### Details

Currently, the select button is really small and easy to miss, I'm suggesting to change its text style (ex: color / italics / underline) or change its button style (ex: background color / outline). Thank you!

(Btw, I think "sort" is used more often than "select" in general? Not an issue once you remember what the function is tho, just a teeny bit confusing at first glance.

**Comment by troyeguo** [comment]
Actually, we have completely redesign the select workflow in the latest developer version. A select icon will appear on the book when hovering and we add a select botton in the context menu when right clicking on the book
