### ISSUE TITLE
Traditional Chinese (zh-TW) Translation (.json)

### ISSUE THREAD

**Issue by angelicachao** [koodo-reader/koodo-reader#1071]
### I've read the translation guide

- [X] Yes

### Language code (Check out this website for more info)

zh-TW

### The name of this language in your native language

繁體中文

### Translation snippets or file

Corrected some and filled in the rest. Hopefully they're aren't any typos, not really used to typing in Chinese.
[translation.json](https://github.com/koodo-reader/koodo-reader/files/14189451/translation.json)

**Comment by troyeguo** [comment]
Thanks for your contribution, merged in a5fd4ec310c1a3a4872490f51ac9acf831cd9b9c
