### ISSUE TITLE
两个问题：1、MOBI文件一直没有封面，不知道是设置问题还是个本来就没有。2、能否开发多书架功能，各书架单独导入（可以设上限），用户自己命名。

### ISSUE THREAD

**Issue by xlg1018** [koodo-reader/koodo-reader#1076]
### 我已经搜索了 Issue 列表，没有找到类似的需求

- [X] Yes

### 如果您有不止一个需求，请在多个 issue 里分别提交.

- [X] Yes

### 简单介绍

如题头

### 细节描述

1、MOBI文件一直没有封面，不知道是设置问题还是个本来就没有。
2、能否开发多书架功能，各书架单独导入（可以设上限），用户自己命名。

**Comment by troyeguo** [comment]
最新开发版这两个功能都已经支持，导入前需要先切换到该书架

**Comment by LaYue-XunMei** [comment]
mobi文件可以自定义封面了吗，没有找到怎么设置
