### ISSUE TITLE
Complete-it-IT-translation.json

### ISSUE THREAD

**Issue by dunnomane** [koodo-reader/koodo-reader#1088]
### I've read the translation guide

- [X] Yes

### Language code (Check out this website for more info)

it-IT

### The name of this language in your native language

it-IT

### Translation snippets or file

[translation.json](https://github.com/koodo-reader/koodo-reader/files/14439800/translation.json)

**Comment by troyeguo** [comment]
Thanks for your contribution, merged in 277b0c6a27079bc15432ef859b5233c58d2aea7e
