### ISSUE TITLE
Translation Update - German | de

### ISSUE THREAD

**Issue by kotokod** [koodo-reader/koodo-reader#1094]
### I've read the translation guide

- [X] Yes

### Language code (Check out this website for more info)

de

### The name of this language in your native language

German

### Translation snippets or file

Hello Koodo-people :-)

as i can see great potential in this project and figured it would be good to contribute somehow... 

So because i'm not a programmer but studied linguistics, i updated the german translation file with some fixes and translation for the unfinished parts. There are some minor spots which i left out, because the context wasn't clear to me. But i hope this translation is of use for the project. 
 Keep it up! :-)
[translation.json](https://github.com/koodo-reader/koodo-reader/files/14482074/translation.json)

**Comment by troyeguo** [comment]
Thanks for your contribution, we have finished the rest with the help of Deepl. Merged in https://github.com/koodo-reader/koodo-reader/commit/3de75502414df89be564eb4d05e89f9e156270a5
