### ISSUE TITLE
1.6.5 armenian translation

### ISSUE THREAD

**Issue by dorianissimo** [koodo-reader/koodo-reader#1102]
### I've read the translation guide

- [X] Yes

### Language code (Check out this website for more info)

hy

### The name of this language in your native language

Հայերեն

### Translation snippets or file

[translation.json](https://github.com/koodo-reader/koodo-reader/files/14632488/translation.json)

**Comment by troyeguo** [comment]
Thanks for your contribution, merged in https://github.com/koodo-reader/koodo-reader/commit/fcc8a6f014f20b1bf5c1b2b2dacc0761905646d5
