### ISSUE TITLE
Complete translation of Vietnamese json

### ISSUE THREAD

**Issue by nhantruongvn** [koodo-reader/koodo-reader#1106]
### I've read the translation guide

- [X] Yes

### Language code (Check out this website for more info)

vi

### The name of this language in your native language

Tiếng Việt

### Translation snippets or file

{
  "Books": "Sách",
  "Recent": "Gần đây",
  "Bookmarks": "Dấu trang",
  "Favorites": "Yêu thích",
  "Notes": "Ghi chú",
  "Highlights": "Highlight",
  "Shelf": "Kệ sách",
  "Left": "Canh trái",
  "Justify": "Canh đều",
  "Right": "Canh phải",
  "Text alignment": "Canh lề",
  "Synchronisation successful": "Đồng bộ hóa thành công",
  "Permanently Delete": "Xóa vĩnh viễn",
  "Default search engine": "Công cụ tìm kiếm mặc định",
  "Built-in font": "Font chữ mặc định",
  "Cover": "Trang bìa",
  "Bold": "In đậm",
  "Sort by": "Sắp xếp",
  "Italic": "In nghiêng",
  "Underline": "Gạch chân",
  "Shadow": "Đổ bóng chữ",
  "Import failed": "Nhập lỗi",
  "New version available": "Đã có phiên bản mới",
  "New version": "Phiên bản mới",
  "Customize": "Tùy chỉnh",
  "Auto open book in fullscreen": "Tự động mở sách ở chế độ toàn màn hình",
  "System font": "Font chữ hệ thống",
  "Access token expired, refetching token": "Mã truy cập quá hạn, lấy mã truy cập mới",
  "Access token received, please continue": "Đã nhận mã truy cập, vui lòng tiếp tục",
  "Change log": "Nhật ký thay đổi",
  "Update complete": "Cập nhật hoàn tất",
  "Fetching acess token failed": "Truy xuất mã truy cập không thành công",
  "Authorizing, please wait": "Đang xác thực, vui lòng đợi",
  "Downloading, please wait": "Đang tải xuống, vui lòng đợi",
  "Uploading, please wait": "Đang tải lên, vui lòng đợi",
  "Import": "Nhập",
  "Backup": "Backup",
  "Search my library": "Tìm kiếm trong thư viện của tôi",
  "Search my notes": "Tìm kiếm ghi chú của tôi",
  "Search my highlights": "Tìm kiếm highlight của tôi",
  "Card": "Thẻ",
  "List": "Danh sách",
  "Work": "Công việc",
  "Entertainment": "Giải trí",
  "Study": "Học tập",
  "Author": "Tác giả",
  "Duplicate shelf": "Kệ sách trùng lặp",
  "Reading time": "Thời gian đọc",
  "Content": "Nội dung",
  "Voice": "Giọng nói",
  "Speed": "Tốc độ",
  "Bookmark": "Dấu trang",
  "Single": "Chế độ trang đơn",
  "Double": "Chế độ trang đôi",
  "Background color": "Màu nền",
  "Font size": "Kích thước chữ",
  "Font family": "Kiểu chữ",
  "Default": "Mặc định",
  "Small": "Nhỏ",
  "Medium": "Vừa",
  "Large": "Lớn",
  "Cancellation successful": "Hủy bỏ thành công",
  "Only supported by desktop version": "Chỉ hỗ trợ phiên bản trên máy tính",
  "Auto hide cursor when reading": "Tự động ẩn trỏ chuột trong khi đọc",
  "Disable update notification": "Tắt thông báo cập nhật",
  "Roadmap": "Lộ trình dự kiến",
  "Paragraph spacing": "Cách đoạn",
  "Unlock": "Mở khóa",
  "Lock": "Khóa",
  "Reading option": "Điều chỉnh chế độ đọc",
  "Progress": "Tiến độ",
  "Exit": "Thoát",
  "Language": "Ngôn ngữ",
  "Enter Fullscreen": "Mở chế độ toàn màn hình",
  "Exit Fullscreen": "Thoát chế độ toàn màn hình",
  "Add to shelf": "Thêm vào kệ",
  "New shelf": "Kệ sách mới",
  "New": "Mới",
  "Cancel": "Hủy",
  "Confirm": "Xác nhận",
  "Delete": "Xóa",
  "Delete this book": "Xóa sách này",
  "Edit Book": "Sửa",
  "Edition successful": "Sửa thành công",
  "Book name": "Tên sách",
  "Sort by Date": "Thêm thời gian",
  "Book not exist": "Sách không tồn tại",
  "Copy link": "Sao chép đường dẫn",
  "Copied": "Đã sao chép",
  "Search the book": "Tìm kiếm",
  "Loading": "Đang tải",
  "Note": "Ghi chú",
  "Page width": "Chiều dài trang",
  "Turn on successful": "Bật thành công",
  "Turn off successful": "Tắt thành công",
  "Setting": "Cài đặt",
  "Developer": "Nhà phát triển",
  "Please import less than 10 books": "Hãy nhập ít hơn 10 sách",
  "Please delete some books before import": "Hãy xóa một số sách trước khi nhập thêm",
  "For better user experince, please visit this site on a computer": "Để có trải nghiệm tốt hơn, hãy đến trang này trên máy tính",
  "Last step": "Bước trước",
  "Next step": "Bước tiếp theo",
  "Go to": "Đến",
  "Return to home": "Trở về trang chủ",
  "Pages": "Trang",
  "Chapters": "Chương",
  "Translate": "Dịch",
  "Pick a color": "Chọn màu",
  "Highlighting successful": "Highlight thành công",
  "Highlight": "Highlight",
  "Copying successful": "Copy thành công",
  "Copy ": "Copy",
  "Text color": "Màu chữ",
  "Export": "Xuất",
  "Description": "Miêu tả",
  "Recently read": "Vừa đọc",
  "Collapse sidebar": "Tắt sidebar",
  "Show sidebar": "Hiện sidebar",
  "Sync": "Đồng bộ",
  "Help": "Tài liệu",
  "Feedback": "Feedback",
  "Github Repo": "Github Repo",
  "Search on the Internet": "Tìm kiếm trên internet",
  "Search in the Book": "Tìm trong sách",
  "Change storage location": "Thay đổi chỗ lưu trữ",
  "Change location": "Thay đổi",
  "Change successful": "Thay đổi thành công",
  "Export successful": "Xuất thành công",
  "Change failed": "Thay đổi thất bại",
  "Deleted Books": "Thùng rác",
  "Delete all books": "Xóa tất cả sách",
  "Please choose an empty folder": "Hãy chọn folder trống",
  "Empty library": "Thư viện rỗng",
  "Download": "Tải xuống",
  "Turn on night mode": "Bật night mode",
  "Turn on auto update": "Bật tự động cập nhật",
  "Take effect at next startup": "Khởi động lại để áp dụng thay đổi",
  "View mode": "View mode",
  "Download desktop version": "Tải phiên bản Desktop",
  "No favorite books": "Không  có sách ưa thích",
  "Empty bookmark": "Chưa Bookmark nào",
  "Empty note": "Chưa Note nào",
  "Blue": "Xanh nước biển",
  "Red": "Đỏ",
  "Green": "Xanh lá cây",
  "Purple": "Tím",
  "Download Demo Book": "Tải sách Demo",
  "More": "Thêm",
  "Copy": "Copy",
  "Hi! stranger": "Xin chào! Người lạ",
  "Sync data from storage": "Đồng bộ dữ liệu từ storage",
  "Click on any book to read": "Nhấn vào sách bất kỳ để đọc",
  "Select all": "Chọn tất cả",
  "Error happened": "Có lỗi",
  "Open book without adding it to library": "Mở sách mà không thêm vào thư viện",
  "Use first page as PDF cover": "Dùng trang đầu cho bìa file PDF",
  "Light mode": "Giao diện sáng",
  "Night mode": "Giao diện tối",
  "Follow OS": "Theo giao diện thiết bị",
  "Latest stable version": "Phiên bản ổn định mới nhất",
  "Translation": "Dịch",
  "Auto open book in full screen": "Tự động mở sách ở chế độ toàn màn hình",
  "Hide mimical background": "Hide mimical background",
  "Enter full screen": "Vào chế độ toàn màn hình",
  "Exit full screen": "Thoát chế độ toàn màn hình",
  "Full screen": "Chế độ toàn màn hình",
  "Descend": "Giảm dần",
  "Ascend": "Tăng dần",
  "Token": "Mã truy cập",
  "Please authorize your account, and fill the following box with the token": "Vui lòng cho quyền tài khoản của bạn, và điền mã truy cập vào ô sau",
  "Copy token": "Copy mã truy cập",
  "Conversoin of Chinese": "Conversoin of Chinese",
  "Shelf title can't be pure number": "Tên kệ sách không thể chỉ toàn là số",
  "Open console": "Mở bàn điều khiển",
  "Appearance": "Hình dạng",
  "Open url with built-in browser": "Mở URL bằng trình duyệt tích hợp",
  "Turn on bionic reading": "Bật phương pháp Bionic Reading",
  "This process is inreversible, and will completely overwrite your current library, make sure you know what you're doing before proceeding": "Quá trình này sẽ ghi đè hoàn toàn thư viện hiện tại của bạn và không thể đảo ngược, cân nhắc trước khi tiếp tục",
  "Lemmatize words when looking up in a dictionary": "Sử dụng gốc từ khi tra từ điển",
  "To reduce the different forms of a word to one single form, for example, reducing builds, building or built to build, reducing cats to cat, reducing fastest to fast": "Để giảm các dạng khác nhau của một từ thành một dạng duy nhất, ví dụ: builds, building hoặc built thành build, giảm cats thành cat, giảm fastest thành fast",
  "Export all books": "Xuất tất cả sách",
  "Export all notes": "Xuất tất cả ghi chú",
  "Export all highlights": "Xuất tất cả highlight",
  "Export all dictionary history": "Xuất tất cả lịch sử từ điển",
  "Export dictionary history": "Xuất lịch sử từ điển",
  "Export all": "Xuất tất cả",
  "Export books": "Xuất sách",
  "Export notes": "Xuất ghi chú",
  "Export highlights": "Xuất highlight",
  "Nothing to export": "Không có gì để xuất",
  "More actions": "Nhiều hanh động hơn",
  "Pre-cache": "Lưu trước vào bộ nhớ đệm",
  "Pre-caching": "Bộ nhớ đệm trước",
  "Pre-caching successful": "Lưu trước vào bộ nhớ đệm thành công",
  "Pre-caching failed": "Lưu trước vào bộ nhớ đệm không thành công",
  "Delete pre-cache": "Xóa bộ nhớ đệm",
  "Nothing to precache": "Không có gì để lưu trước vào bộ nhớ đệm",
  "Auto precache books after import": "Tự động lưu trước vào bộ đệm sau khi nhập sách",
  "Pre-cache books after import to increase opening speed, Koodo will generate a precache version of the original book and save it into your library": "Lưu trước vào bộ đệm sau khi nhập để tăng tốc mở, Koodo sẽ tạo phiên bản lưu trước vào bộ đệm của sách gốc và lưu vào thư viện của bạn",
  "Take effect in a while": "Có hiệu lực sau một thời gian",
  "Don't use first page as PDF cover": "Không sử dụng trang đầu tiên làm bìa PDF",
  "Don't crop book cover": "Không cắt bìa sách",
  "Add to favorite": "Thêm vào yêu thích",
  "Remove from favorite": "Xóa khỏi mục yêu thích",
  "Details": "Chi tiết",
  "Multiple selection": "Nhiều lựa chọn",
  "You may see this error when the book you're importing is not supported by Koodo Reader, try converting it with Calibre": "Bạn gặp lỗi này do sách bạn đang nhập không được hỗ trợ bởi Koodo Reader, hãy thử chuyển đổi nó bằng Calibre",
  "Simplified To Traditional": "Giản thể sang Phồn thể",
  "Traditional To Simplified": "Phồn thể sang Giản thể",
  "Shelf Title is Empty": "Tiêu đề kệ còn trống",
  "Link copy successful": "Sao chép liên kết thành công",
  "Addition successful": "Thêm thành công",
  "Select": "Chọn",
  "Coming soon": "Sắp ra mắt",
  "Understand": "Hiểu",
  "Authorisation successful": "Cho quyền thành công",
  "Authorisation failed": "Cho quyền không thành công",
  "Choose your operation": "Chọn hoạt động của bạn",
  "Where is your data?": "Dữ liệu của bạn ở đâu?",
  "Where to keep your data?": "Nơi lưu giữ dữ liệu của bạn?",
  "Restore": "Khôi phục",
  "Delete this shelf": "Xóa kệ sách này",
  "This action will clear and remove this shelf": "Hành động này sẽ xóa kệ sách này",
  "Delete this tag": "Xóa thẻ này",
  "This action will clear and remove this tag": "Hành động này sẽ xóa thẻ này",
  "Backup successful": "Sao lưu thành công",
  "Restore successful": "Khôi phục thành công",
  "Try refresh or restart": "Hãy thử làm mới hoặc khởi động lại",
  "Theme color": "Màu chủ đề",
  "Turn on text-to-speech": "Bật tính năng chuyển văn bản thành giọng nói",
  "Scrolling mode": "Chế độ cuộn",
  "Digest": "Thông báo tóm tắt",
  "Auto expand content": "Tự động mở rộng nội dung",
  "Hide footer": "Ẩn footer",
  "Hide header": "Ẩn tiêu đề",
  "Book size is over 20M": "Kích thước sách trên 20 MB",
  "Current Font size": "Cỡ chữ hiện tại",
  "Current Chapter": "Chương hiện tại",
  "Turn off text-to-speech": "Tắt tính năng chuyển văn bản thành giọng nói",
  "Warning": "Cảnh báo",
  "All tags": "Tất cả các thẻ",
  "Turn off touch screen mode": "Tắt chế độ màn hình cảm ứng (tránh vô tình chạm vào)",
  "Use built-in font": "Sử dụng phông chữ tích hợp",
  "Turn on touch screen mode": "Bật chế độ màn hình cảm ứng",
  "Auto open last-read book": "Tự động mở sách đọc lần cuối",
  "About Project": "Về dự án",
  "Wrong bookmark": "Dấu trang sai",
  "It seems like you're lost": "Có vẻ như bạn đang bị lạc",
  "Only desktop support this format": "Chỉ phiên bản máy tính để bàn hỗ trợ định dạng này",
  "Only desktop support this service": "Chỉ có phiên bản máy tính để bàn hỗ trợ dịch vụ này",
  "Delete from shelf": "Xóa khỏi kệ",
  "Deletion successful": "Xóa thành công",
  "This action will move this book and its the notes, bookmarks and highlights of this book to the recycle bin": "Hành động này sẽ chuyển sách cùng các ghi chú, dấu trang và highlight trong sách vào thùng rác",
  "This action won't delete the original book": "Hành động này sẽ không xóa sách gốc",
  "From": "Từ",
  "Duplicate book": "Sách trùng lặp",
  "Unknown chapter": "Không rõ chương",
  "Unknown author": "Không rõ tác giả",
  "Empty": "Trống",
  "Next chapter": "Chương sau",
  "Previous chapter": "Chương trước",
  "Less": "Ít hơn",
  "Developer version": "Phiên bản dành cho nhà phát triển",
  "Current reading time": "Thời gian đọc: {{count}} phút",
  "Remaining reading time": "Thời gian còn lại: {{count}} phút",
  "Book page": "Trang {{count}}",
  "Total books": "Tổng số {{count}} sách",
  "Continuous": "Tiếp diễn",
  "Scroll": "Cuộn",
  "Show in the book": "Hiển thị trong sách",
  "More notes": "Thêm ghi chú",
  "Take a note": "Ghi chú lại",
  "Publisher": "Nhà xuất bản",
  "Added on": "Đã thêm vào",
  "Margin": "Lề",
  "Do you want to open this link in browser": "Bạn có muốn mở liên kết này trong trình duyệt không",
  "WebDAV Info": "WebDAV là giải pháp sao lưu dễ sử dụng và hiệu quả, chúng tôi khuyên bạn nên sử dụng dịch vụ WebDAV do NextCloud cung cấp",
  "Please wait": "Vui lòng chờ",
  "Server address": "Địa chỉ máy chủ",
  "Username": "Tên tài khoản",
  "Password": "Mật khẩu",
  "Document": "Tài liệu",
  "GitHub repository": "GitHub repository",
  "Speak the text": "Đọc văn bản",
  "Too many images": "Sách có quá nhiều hình ảnh",
  "You successfully update to": "Bạn đã cập nhật thành công",
  "Reading duration": "Thời lượng đọc",
  "Author name": "Tên tác giả",
  "Audio is not ready yet": "Tính năng chuyển văn bản thành giọng nói vẫn chưa sẵn sàng",
  "Drop your books here": "Hãy thả sách của bạn vào đây",
  "Reading progress": "Tiến độ đọc",
  "This action will remove all the books in recycle bin,together with their notes, bookmarks and digests": "Hành động này sẽ xóa vĩnh viễn tất cả sách trong thùng rác cùng với ghi chú, dấu trang và thông báo của chúng",
  "Batch import only support epub or pdf files": "Nhập hàng loạt chỉ hỗ trợ tệp ePub và pdf",
  "The deleted books will show up here": "Những sách đã xóa sẽ hiển thị ở đây",
  "Empty recycle bin": "Làm rỗng thùng rác",
  "Skip": "Bỏ qua",
  "Local": "Cục bộ",
  "Tips": "Lời khuyên",
  "Brightness": "Độ sáng",
  "How synchronisation works": "Cách đồng bộ hóa hoạt động",
  "Sync function works with third-party cloud drive. You need to manually change the storage location to the same sync folder on different computers. When you click the sync button, Koodo Reader will automatically upload or download the data from this folder according the timestamp.": "Chức năng đồng bộ hóa hoạt động với dịch lưu trữ đám mây của bên thứ ba. Bạn hãy thay đổi vị trí lưu trữ cùng thư mục lưu trữ đám mây trên máy tính. Khi bạn nhấp vào nút Đồng bộ hóa, Koodo Reader sẽ tự động tải lên hoặc tải xuống dữ liệu của bạn từ thư mục này và giữ cho dữ liệu được đồng bộ hóa trên các thiết bị. Hãy truy cập tài liệu của chúng tôi để được hướng dẫn thêm.",
  "Line height": "Chiều cao giữa các dòng",
  "Please turn off open books in the main window first": "Vui lòng đóng sách đang mở trong cửa sổ chính trước",
  "Please turn off merge with word first": "Vui lòng tắt Hợp nhất trình đọc với Word trước",
  "Data change detected, whether to update?": "Đã phát hiện thay đổi dữ liệu. Bạn có muốn cập nhật không?",
  "Use the fonts from your local computer": "Sử dụng phông chữ trên máy tính của bạn",
  "Backup your data with WebDAV": "Sao lưu dữ liệu của bạn với WebDAV",
  "Click the import button to add books": "Bấm Nhập để thêm sách",
  "Auto Update relies on GitHub Release for package hosting, if your internet doesn't have stable connection to GitHub, we highly recommand you to turn off this option": "Cập nhật tự động dựa vào Bản phát hành GitHub để lưu trữ gói, nếu bạn không có kết nối Internet ổn định với GitHub, chúng tôi khuyên bạn nên tắt tùy chọn này",
  "File size": "Kích thước tệp",
  "Prototype": "Nguyên mẫu",
  "Right click on any book and click Add to favorite to add it to your favorite books": "Nhấp chuột phải vào sách bất kỳ và nhấp Thêm vào mục yêu thích để thêm nó vào những sách yêu thích của bạn",
  "Empty reading records": "Làm trống báo cáo",
  "Select any text and click the note button on the popup menu": "Chọn đoạn văn bản bất kỳ và nhấp vào Ghi chú trên menu bật lên",
  "Empty highlight": "Làm trống highlight",
  "Select any text and click the highlight button on the popup menu": "Chọn đoạn văn bản bất kỳ và nhấp vào Highlight trên menu bật lên",
  "Invert color": "Đảo ngược màu",
  "Empty shelf": "Làm trống kệ",
  "Move your mouse on top of any book, then click the more icon to add the book to the shelf": "Di chuyển chuột lên một sách bất kỳ, sau đó nhấp vào biểu tượng thêm để thêm sách vào kệ",
  "Download failed, network problem or no backup": "Tải xuống không thành công, sự cố mạng hoặc không có bản sao lưu",
  "Upload failed, check your connection": "Tải lên không thành công, hãy kiểm tra kết nối của bạn",
  "Version": "Phiên bản: ",
  "Not supported yet": "Chưa được hỗ trợ",
  "Update to": "Cập nhật lên",
  "Date": "Ngày:",
  "Unauthorize": "Hủy cho quyền",
  "Remember window's size": "Ghi nhớ kích thước cửa sổ",
  "Letter spacing": "Khoảng cách chữ",
  "Unauthorize successful": "Hủy cho quyền thành công",
  "Extra large": "Cực lớn",
  "Ultra large": "Siêu lớn",
  "Disable analytics service": "Tắt dịch vụ phân tích",
  "Hide navigation button": "Ẩn nút điều hướng",
  "Collect": "Sưu tầm",
  "Move your mouse on the top edge of the reader": "Di chuyển chuột lên đầu trình đọc",
  "Download failed,network problem or no backup": "Tải xuống không thành công, sự cố mạng hoặc không có bản sao lưu",
  "Choose your action to this book": "Bạn muốn làm gì với sách này",
  "Edit": "Biên tập",
  "Add": "Thêm",
  "Survey": "Khảo sát",
  "What's new about this version": "Phiên bản này có gì mới",
  "Our website": "Website của chúng tôi",
  "What's new": "Có gì mới",
  "What's been fixed": "Những gì được sửa",
  "Target": "Mục tiêu",
  "Execute successful": "Thực hiện thành công",
  "Disable screen blanking": "Tắt tính năng xóa màn hình",
  "When Koodo is running, your computer won't enter sleep mode": "Khi Koodo đang chạy, máy tính sẽ không vào chế độ ngủ",
  "Prevent accidental trigger": "Ngăn chặn kích hoạt do tình cờ",
  "Import books as link": "Nhập sách dưới dạng đường dẫn",
  "Close main window while reading": "Đóng cửa sổ chính trong khi đọc",
  "Merge reader into Word": "Hợp nhất trình đọc vào Word",
  "Get rid of window frame, make reader hide into Word or any text editor, and can't be detected. You need to set up the reader's position, size and style first.": "Loại bỏ khung cửa sổ, khiến trình đọc ẩn vào Word hoặc bất kỳ trình soạn thảo khác và không thể bị phát hiện. Trước tiên, bạn cần thiết lập vị trí, kích thước và kiểu dáng của trình đọc.",
  "The imported books will not be copied to library, only linked to the original book path": "Sách đã nhập sẽ không được sao chép vào thư viện mà chỉ liên kết với đường dẫn sách gốc",
  "Reader menu will not be triggered by hovering but clicking on the area": "Menu của trình đọc sẽ không được kích hoạt bằng cách di chuột mà nhấp vào khu vực",
  "Gesture and UI optimization for touch screen": "Tối ưu hóa cử chỉ và giao diện người dùng cho màn hình cảm ứng",
  "The book that you read from last time will be open automatically when launching": "Sách lần cuối bạn đọc sẽ tự động mở khi khởi chạy",
  "All the folded content will be expanded in the navigation panel": "Tất cả các mục con sẽ được xổ ra trong bảng điều hướng",
  "Reader window will be maximized to fit the screen when opening a book": "Cửa sổ trình đọc sẽ được phóng to tối đa để vừa với màn hình khi mở sách",
  "Open books in the main window": "Mở sách trong cửa sổ chính",
  "Book won't be opened in a separate window but directly opened in the main window": "Sách sẽ không được mở trong cửa sổ riêng mà mở trực tiếp trong cửa sổ chính",
  "Frequency limit reached": "Đã đạt đến giới hạn tần số",
  "Text indentation": "Thụt lề văn bản",
  "Deselect all": "Bỏ chọn tất cả",
  "Authorize": "Cho quyền",
  "When opening books in the file manager with Koodo, the opened books won't be added to the library": "Khi mở sách trong trình quản lý tệp bằng Koodo, sách đã mở sẽ không được thêm vào thư viện",
  "Hide menu button": "Ẩn nút menu",
  "Manage": "Quản lý",
  "Sliding animation": "Hoạt ảnh trượt",
  "Please turn off open books in the main window": "Vui lòng đóng sách đang mở trong cửa sổ chính",
  "This action will delete all the notes, bookmarks and digests of this book": "Hành động này sẽ xóa tất cả ghi chú, dấu trang và thông báo tóm tắt của sách này",
  "More formats supported": "Hỗ trợ nhiều định dạng hơn",
  "Koodo Reader's web version are limited by the browser, for more powerful features, please download the desktop version.": "Phiên bản web của Koodo Reader bị giới hạn bởi trình duyệt, để có thêm các tính năng mạnh mẽ hơn, vui lòng tải xuống phiên bản dành cho máy tính để bàn.",
  "No popup when selecting texts": "No popup when selecting texts",
  "Turn it on when you want Koodo to work with other third-party translation service, right clicking on the selected text will trigger popup again": "Bật nó lên khi bạn muốn Koodo làm việc với dịch vụ dịch thuật của bên thứ ba, nhấp chuột phải vào văn bản đã chọn sẽ kích hoạt lại cửa sổ bật lên",
  "Disable trash bin": "Vô hiệu hóa thùng rác",
  "When deleting books, they will be deleted permanently instead of sending to trash bin": "Khi xóa, sách sẽ bị xóa vĩnh viễn thay vì bị đưa vào thùng rác",
  "Hide books already added to the shelf": "Ẩn sách đã được thêm vào kệ",
  "Hide books which have been added to the shelf, so they won't show up in home page": "Ẩn sách đã được thêm vào kệ để chúng không hiển thị trên trang chủ",
  "Delete book from shelf also deleting book itself": "Xóa sách khỏi kệ đồng thời xóa tệp của sách đó",
  "When deleting book from shelf, the book will be deleted as well": "Khi xóa sách khỏi kệ, tệp của sách đó cũng sẽ bị xóa",
  "This action will permanently delete the selected books, together with their notes, bookmarks and digests": "Hành động này sẽ xóa vĩnh viễn những sách đã chọn cùng với ghi chú, dấu trang và thông báo của chúng",
  "Server Path": "Đường dẫn máy chủ",
  "Use SSL, 1 for use, 0 for not use": "Sử dụng SSL, 1 nếu sử dụng, 0 nếu không sử dụng",
  "Server port": "Cổng máy chủ",
  "Sending successful": "Gửi thành công",
  "Sending": "Đang gửi",
  "Thanks for using the developer version, leave a comment if you encounter any problems. Note that we can't reply to you from here. For faster and better support, please visit": "Cảm ơn bạn đã sử dụng phiên bản dành cho nhà phát triển, hãy để lại nhận xét nếu gặp bất kỳ vấn đề nào. Lưu ý rằng chúng tôi không thể trả lời bạn từ đây. Để được hỗ trợ nhanh hơn và tốt hơn, vui lòng truy cập",
  "You're not using the latest version of Koodo Reader. Please update first": "Bạn hiện không sử dụng phiên bản mới nhất của Koodo Reader. Vui lòng cập nhật trước",
  "Brief description of the problem": "Mô tả ngắn gọn vấn đề",
  "Detailed description of the problem": "Mô tả chi tiết vấn đề",
  "Your email(optional), We may contact you for further investigation": "Email của bạn (tùy chọn), Chúng tôi có thể liên hệ với bạn để khảo sát thêm",
  "Report": "Báo cáo",
  "Sentence": "Câu",
  "Associations": "Liên kết",
  "Explanations": "Giải thích",
  "Pronunciations": "Cách phát âm",
  "Upload attachments": "Tải lên tệp đính kèm",
  "File size is larger than 20MB": "Kích thước tệp lớn hơn 20MB",
  "Learn more": "Tìm hiểu thêm",
  "Format": "Định dạng",
  "Duplicate book in trash bin": "Sách trùng lặp trong thùng rác",
  "Subject can't be empty": "Chủ đề không được để trống"
}

**Comment by nhantruongvn** [comment]
I tried to create a branch and a pull request. But I don't have access right to the repo.

**Comment by troyeguo** [comment]
Thanks for your contribution, merged in https://github.com/koodo-reader/koodo-reader/commit/2a95a2ab9b38826f323166a256a977c4f2005432
