### ISSUE TITLE
epub格式文字使用内嵌字体时，无法显示出正确的内嵌格式。

### ISSUE THREAD

**Issue by Guo-ShiKuan** [koodo-reader/koodo-reader#111]
同一文件测试：neat reader 会显示出电子书中预设的宋体和楷体之类的字体，但是Koodo reader默认为类似黑体的字体。

**Comment by troyeguo** [comment]
麻烦您提供一下电子书文件

**Comment by Guo-ShiKuan** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "troyeguo/koodo-reader"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月6日(星期二) 上午8:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [troyeguo/koodo-reader] epub格式文字使用内嵌字体时，无法显示出正确的内嵌格式。 (#111)





 
麻烦您提供一下电子书文件

**Comment by troyeguo** [comment]
您提供的电子书《下沉年代》没有看到有内嵌字体，您可以再提供一本吗？

**Comment by Guo-ShiKuan** [comment]
这本书中是存在楷体的------------------&nbsp;原始邮件&nbsp;------------------



这是neat reader和koboo reader两个使用内嵌字体时，显示的不同。
发件人:                                                                                                                        "troyeguo/koodo-reader"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月11日(星期天) 下午3:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [troyeguo/koodo-reader] epub格式文字使用内嵌字体时，无法显示出正确的内嵌格式。 (#111)





 
您提供的电子书《下沉年代》没有看到有内嵌字体，您可以再提供一本吗？

**Comment by Guo-ShiKuan** [comment]
我有一个地方可能弄错了，应该说是内置字体，而不是内嵌字体。
希望可以实现内置字体显现的方式，比如neat reader那样。
对您造成的困扰，感到抱歉。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "troyeguo/koodo-reader"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月11日(星期天) 下午3:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [troyeguo/koodo-reader] epub格式文字使用内嵌字体时，无法显示出正确的内嵌格式。 (#111)





 
您提供的电子书《下沉年代》没有看到有内嵌字体，您可以再提供一本吗？

**Comment by troyeguo** [comment]
我用neat-reader查看了《下沉年代》这本书，确实没找到哪里有楷体，您可以复制一段使用楷体的文字过来吗，我再全文搜索一下

**Comment by Guo-ShiKuan** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "troyeguo/koodo-reader"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月11日(星期天) 晚上8:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [troyeguo/koodo-reader] epub格式文字使用内嵌字体时，无法显示出正确的内嵌格式。 (#111)





 
我用neat-reader查看了《下沉年代》这本书，确实没找到哪里有楷体，您可以复制一段使用楷体的文字过来吗，我再全文搜索一下
