### ISSUE TITLE
1.6.5版Koodo Reader能够支持PDF笔记、批注功能吗？

### ISSUE THREAD

**Issue by Sun12Xq** [koodo-reader/koodo-reader#1112]
### 我已经搜索了 Issue 列表，没有找到类似的需求

- [X] Yes

### 我已经试用最新开发版，同样没找到这个功能

- [X] Yes

### 如果您有不止一个需求，请在多个 issue 里分别提交.

- [X] Yes

### 简单介绍

用1.6.5版Koodo Reader阅读PDF书籍，不能够做笔记、批注，而阅读epub书籍则可以做高亮标记和进行批注，希望对于PDF书籍也能够可以。

### 细节描述

用1.6.5版Koodo Reader阅读PDF书籍，不能够做笔记、批注，而阅读epub书籍则可以做高亮标记和进行批注，希望对于PDF书籍也能够可以。

**Comment by troyeguo** [comment]
请先确保pdf文件不是扫描版，文字版已经支持
