### ISSUE TITLE
导出高亮，导出笔记

### ISSUE THREAD

**Issue by Henryhurryup** [koodo-reader/koodo-reader#1114]
### 我已经搜索了 Issue 列表，没有找到类似的需求

- [X] Yes

### 我已经试用最新开发版，同样没找到这个功能

- [X] Yes

### 如果您有不止一个需求，请在多个 issue 里分别提交.

- [X] Yes

### 简单介绍

希望可以导出我的笔记和我的高亮

### 细节描述

有按键，可以一键导出 笔记和高亮，方便整理

**Comment by troyeguo** [comment]
这个功能已经在最新开发版中支持了

**Comment by lionking293** [comment]
> 这个功能已经在最新开发版中支持了

哪个版本？1.51中没有发现这个功能。

**Comment by lionking293** [comment]
找到了。谢谢！



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年12月28日 08:55 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [koodo-reader/koodo-reader] 导出高亮，导出笔记 (Issue #1114) |

这个功能已经在最新开发版中支持了

哪个版本？1.51中没有发现这个功能。

最新开发版是1.7.2，您可以前往官网下载
