### ISSUE TITLE
What is the file name of configuration saved ?

### ISSUE THREAD

**Issue by Augusto7743** [koodo-reader/koodo-reader#1117]
### I've searched the issue list, there are no similar features.

- [X] Yes

### I've installed the latest developer version, still can't find this feature.

- [X] Yes

### If you have more than one feature, please open multiple issues.

- [X] Yes

### Brief Introduction

Hello. Thanks for reading my topic.
I want save the Koodo Reader's configuration file Linux version from /home/username/.config/koodo-reader/ to an restore when needed.
What is the name of configuration ?

### Details

Have an nice day.

**Comment by troyeguo** [comment]
You can click the Sync button, A zip file named config.zip will be generated in the same location.
