### ISSUE TITLE
希望能有沉浸式阅读功能，复制文字的到别的地方时候两边总是自动弹出

### ISSUE THREAD

**Issue by South-Brid** [koodo-reader/koodo-reader#1126]
### 我已经搜索了 Issue 列表，没有找到类似的需求

- [X] Yes

### 我已经试用最新开发版，同样没找到这个功能

- [X] Yes

### 如果您有不止一个需求，请在多个 issue 里分别提交.

- [X] Yes

### 简单介绍

希望可以开关目录的弹出和阅读选项的弹出

### 细节描述

当我使用软件看书，将一段文字复制到别的地方，当我鼠标经过两侧边界总是能弹出目录和阅读选项的设置。这令我很困扰，我希望有个按钮，或者有个地方能控制其两遍弹出

**Comment by troyeguo** [comment]
请在设置开启防误触模式
