### ISSUE TITLE
Added Hindi language for Translation

### ISSUE THREAD

**Issue by anujbalak** [koodo-reader/koodo-reader#1143]
### I've read the translation guide

- [X] Yes

### Language code (Check out this website for more info)

hi

### The name of this language in your native language

Hindi

### Translation snippets or file

[translation.json](https://github.com/koodo-reader/koodo-reader/files/15209474/translation.json)

**Comment by troyeguo** [comment]
Thanks for your contribution, merged in https://github.com/koodo-reader/koodo-reader/commit/5d3165d67b6479247911bd35081af514a7dd9303
