### ISSUE TITLE
多个PDF窗口合并问题

### ISSUE THREAD

**Issue by LOCK-TRAIN** [koodo-reader/koodo-reader#1247]
### 我已经搜索了 Issue 列表，没有找到类似的需求

- [ ] Yes

### 我已经试用最新开发版，同样没找到这个功能

- [X] Yes

### 如果您有不止一个需求，请在多个 issue 里分别提交.

- [X] Yes

### 简单介绍

当打开两个或三个PDF文件时，窗口切换不方便。

### 细节描述

1、同时打开多个PDF文档时可否通过拖动或右键设置把多个文档合并到一个窗口里，通过切换Tab来实现不同PDF的阅读切换。
2、另外实际使用时发现鼠标滚轮放大缩小会有第一次滚动时无法缩放的问题，需要二次滚动才生效。

**Comment by ummm288** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
