### ISSUE TITLE
希望书架支持多选编辑

### ISSUE THREAD

**Issue by moleng09** [koodo-reader/koodo-reader#198]
### I've read Koodo's roadmap, there is no similar feature.

- [X] Yes

### This issue only requests one feature.

- [X] Yes

### Brief Introduction

方便图书整理

### Details

类似这样
![Snipaste_2021-08-23_15-48-59](https://user-images.githubusercontent.com/54031747/130410562-916699e7-ba8b-44ac-aeba-f471a8c2c9ad.png)

**Comment by troyeguo** [comment]
感谢您的建议，会在后续版本增加这个功能
