### ISSUE TITLE
Full screen button becomes unresponsive

### ISSUE THREAD

**Issue by gosndka** [koodo-reader/koodo-reader#258]
### I've already installed the latest developer version of Koodo Reader, this problem still exsits

- [X] Yes

### There are no similar issues on the issue list

- [X] Yes

### I've already read the Q&A document, still can't solve it.

- [X] Yes

### Operating System

Windows

### App Version

1.3.4

### Bug Detail

Hello, I seem to having problem going fullscreen for ex: when I click on the fullscreen button after opening a ebook, the fullscreen button unresponsive, Is this is a bug? or the problem is on my end

Can anyone please help me out?

**Comment by troyeguo** [comment]
You may encounter this bug when you exit fullscreen by pressing ESC, then you can't enter fullscreen again by clicking fullscreen button. But This situation only won't happen if you don't use ESC key.

**Comment by gosndka** [comment]
> 
> 
> You may encounter this bug when you exit fullscreen by pressing ESC, then you can't enter fullscreen again by clicking fullscreen button. But This situation only won't happen if you don't use ESC key.

That also happens but sometimes it also happens when I run/open the ebook for the very 1st time, then can is this bug be resolved?

**Comment by troyeguo** [comment]
Sorry, we can't reproduce this bug. some screenshots or videos will help us navigate this issue.

**Comment by poznianski** [comment]
I can confirm. Fullscreen button doesn't work. Version 1.3.9, Windows 11. 

BUT! If you run Koodo as administrator - there is no such problem.

**Comment by gosndka** [comment]
@troyeguo this issue still remains even after 2 years after reporting now esc key doesn't even work for entering into fullscreen

**Comment by troyeguo** [comment]
> @troyeguo this issue still remains even after 2 years after reporting and has gotten worse full screen button doesn't even work now nor esc keybind even work for entering into fullscreen

Thanks for the feedback, we will fix it in the next update
