### ISSUE TITLE
目录的下拉的滑块太小了

### ISSUE THREAD

**Issue by microchitose** [koodo-reader/koodo-reader#275]
### 我已经阅读了Koodo的开发计划，没有找到类似的需求

- [ ] Yes

### 这个Issue没有同时提多个需求.

- [ ] Yes

### 简单介绍

电脑4k屏上鼠标不好瞄准，而且因为滑块在边缘，如果没按准移到菜单外面就自动缩回去了，

### 细节描述

希望能加大加粗滑块或者把滑块移到菜单左边

**Comment by troyeguo** [comment]
感谢您的反馈，会在后续版本优化这个问题。
