### ISSUE TITLE
字体设置中文名字体乱码

### ISSUE THREAD

**Issue by szxypi** [koodo-reader/koodo-reader#318]
### I've already installed the latest developer version of Koodo Reader, this problem still exsits

- [X] Yes

### There are no similar issues on the issue list

- [X] Yes

### I've already read the document, still can't solve it.

- [X] Yes

### Operating system or browser

Windows 10 and below

### App Version

1.4.0

### Bug Detail

![image](https://user-images.githubusercontent.com/42827145/148316184-9fbf7665-40a4-440a-a6bd-d4cb2ee4b974.png)

**Comment by zeroxia** [comment]
Same issue here on Windows 10, English version, with locale set to Chinese simplified.
