### ISSUE TITLE
Allow disable the pop-up menu when selecting a text

### ISSUE THREAD

**Issue by Augusto7743** [koodo-reader/koodo-reader#343]
### I've read Koodo Reader's roadmap, there is no similar feature.

- [X] Yes

### This issue only requests one feature.

- [X] Yes

### Brief Introduction

Tested in Linux

### Details

When selecting a text an menu pop-up is opened above of selected text area with options.
The problem is have times when trying select an area happen error not being possible select and text area and the pop-up menu open creating problem to read the select text aread or even re-select the same area again.
Also when selecting a text area the menu pop-up is opened and few times when pressing CTRL+C not copy the text and need close the pop-up menu to copy the text.
A option to disable enable the pop-up menu or even change the position when the pop-up menu will be opened help to fix it.
Thanks for reply.

**Comment by troyeguo** [comment]
Popup menu already contains copy options. I don't think this feature will make a good user experience for most users.

**Comment by Augusto7743** [comment]
Yes already have copy option.
The problem is when you wish copy several areas and alternating to text editors doing same commands in sequence. Opening the pop-up is more time and need click mouse, but the problem even is when the area is difficulty to select and strangely even holding left mouse when selecting text Koodo Reader fisnish the selection and open the pop-up menu. That issue happen few times and is the because of my posted topic here.
Allowing disable pop-up menu or only opening if user finish the selection and after press right mouse help.
How you even say for default the pop-up menu is displayed, but how have the issue above.
