### ISSUE TITLE
字体bug在1.4.1中并未被正确修复

### ISSUE THREAD

**Issue by lethefrost** [koodo-reader/koodo-reader#367]
### I've already installed the latest developer version of Koodo Reader, this problem still exsits

- [X] Yes

### There are no similar issues on the issue list

- [X] Yes

### I've already read the document, still can't solve it.

- [X] Yes

### Operating system or browser

macOS 12

### App Version

1.4.1

### Bug Detail

您好，原issue被关闭，所以另此提出。

> 请升级至1.4.1

您好，之前提到的I.Ming字体仍然无法使用，只是选择后由“变回苹果默认的黑体”转而“变为一个serif字体（我没认出来，但是可以确认并不是I.Ming）”。谢谢修复！

_Originally posted by @lethefrost in https://github.com/troyeguo/koodo-reader/issues/336#issuecomment-1046027760_

**Comment by troyeguo** [comment]
参考[#中文乱码](https://github.com/oldj/node-font-list/issues/14)，这个问题是上游依赖的问题，我解决不了

**Comment by toyang** [comment]
试下卸载（选删除用户设置）后重新安装呢？我那个issue就是重新安装才好的

**Comment by troyeguo** [comment]
请升级至最新开发版
