### ISSUE TITLE
Mobi格式漫画图片切割问题

### ISSUE THREAD

**Issue by Win888666** [koodo-reader/koodo-reader#459]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10 及以下

### Koodo Reader 版本

1.3.9

### 我遇到的问题

mobi格式下的漫画书用双页模式和单页模式图片会切割错误到下一页，设置里没看到能调图片大小的，请问这是Bug吗？

### 截图或录像(可选的)

![0](https://user-images.githubusercontent.com/105582439/168463781-38d2829b-dce5-4f6f-ae4c-f29e6b7ee390.png)
![1](https://user-images.githubusercontent.com/105582439/168463784-7cac1ff1-4a1d-405b-b2f3-33c5baafdbb7.png)
![2](https://user-images.githubusercontent.com/105582439/168463786-df876343-2d1d-4f77-a4d1-f181a15f402b.png)
![3](https://user-images.githubusercontent.com/105582439/168463788-5100776a-3723-428e-9204-e491fa2e0aed.png)
![4](https://user-images.githubusercontent.com/105582439/168463790-bcd8c489-d855-4559-97ad-04142c494f10.png)

**Comment by visibleLi** [comment]
我也出现了同样的问题 
系统：MacOS 11.5
目前在用滚动模式看漫画
