### ISSUE TITLE
摸鱼模式显示异常

### ISSUE THREAD

**Issue by Kzybd** [koodo-reader/koodo-reader#466]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10 及以下

### Koodo Reader 版本

1.4.4

### 我遇到的问题

普通模式显示正常，进入摸鱼模式后显示滞留，无法使用。

### 截图或录像(可选的)

![image](https://user-images.githubusercontent.com/106131808/169942230-f0bd63f5-c5ed-4b32-91e7-f12c16697d25.png)

### 图书文件(可选的)

[小书痴的下克上WEB 001-627-210815.zip](https://github.com/troyeguo/koodo-reader/files/8759316/WEB.001-627-210815.zip)

**Comment by troyeguo** [comment]
不好意思，我这边没办法复现。
