### ISSUE TITLE
选中的图书数量与实际导入的图书数量不符

### ISSUE THREAD

**Issue by lfk2458** [koodo-reader/koodo-reader#474]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 11

### Koodo Reader 版本

1.3.9

### 我遇到的问题

点击导入从本地导入，在打开的窗口内，全选所有图书后，点击导入，导入软件的图书数量（56本），与全选的图书（11474本）数量不符。

**Comment by caffelab** [comment]
本问题确实存在，不过这么少倒是很离谱，我这边大概五本会进去三本左右，其余两本导入成功后图标出现后，被后面的书本覆盖。

**Comment by technologyrookie** [comment]
我才成功导入4本，再导入就显示图书存在，难顶

**Comment by technologyrookie** [comment]
我才成功导入4本，再导入就显示图书重复，难顶
