### ISSUE TITLE
book not exist

### ISSUE THREAD

**Issue by sixrui** [koodo-reader/koodo-reader#539]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10 及以下

### Koodo Reader 版本

1.3.9

### 我遇到的问题

同步文件夹设置在OneDrive盘中，导入图书点击同步后，在另外一台电脑点击同步，能够看到该图书，但是点击打开时显示book not exist。
未勾选“以引用的方式导入图书”。

**Comment by juliansy** [comment]
有试过在应用中删除该书，再导入吗，我遇到过类似问题，通过这样子解决了。

**Comment by DrJasonhan** [comment]
我也是同样的问题，在Onedrive同步后，书架上能显示图书，但打不开。
我用的1.3.9，无论是否勾选“以引用的方式导入图书”，都不起作用。

**Comment by Joonyvon** [comment]
同样的问题

**Comment by Lz1y** [comment]
同样的问题，看起来是books目录没有被读取，反而被覆盖了
