### ISSUE TITLE
用Magic mouse上下滑动看书的页面一不小心就会连翻很多页，望能控制，否则只能用键盘上下翻页了

### ISSUE THREAD

**Issue by jiangaq** [koodo-reader/koodo-reader#588]
### 我已经阅读了 Koodo Reader 的开发计划，没有找到类似的需求

- [X] Yes

### 这个 issue 没有同时提多个需求.

- [X] Yes

### 简单介绍

如题

### 细节描述

如题

**Comment by troyeguo** [comment]
这个问题暂时没有很好的解决办法，用触控板也存在同样的问题
