### ISSUE TITLE
阅读器左栏目录栏在锁定后仍然会自动隐藏

### ISSUE THREAD

**Issue by sometimessimple** [koodo-reader/koodo-reader#604]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 11

### Koodo Reader 版本

1.4.9

### 我遇到的问题

阅读器左栏目录栏在锁定后仍然会自动隐藏，不能固定显示
希望可以固定左右栏长期显示

**Comment by troyeguo** [comment]
不好意思，我这边没办法复现。您可以提供一下屏幕录像吗？

**Comment by sometimessimple** [comment]
> 

先锁定左栏，点击右栏任意按钮，左栏被折叠隐藏
![image](https://user-images.githubusercontent.com/113500461/196027967-06e8394a-15a6-4e83-a4a6-e586396457ea.png)
