### ISSUE TITLE
GB2312编码支持

### ISSUE THREAD

**Issue by sstiger1230** [koodo-reader/koodo-reader#617]
### 我已经阅读了 Koodo Reader 的开发计划，没有找到类似的需求

- [X] Yes

### 这个 issue 没有同时提多个需求.

- [X] Yes

### 简单介绍

希望支持GB2312编码文件

### 细节描述

TXT文件编码为GB2312，打开乱码。 文件转码UTF-8后一切正常。

因为UTF-8文件比GB2312要增大不少，在某些情况下还是有需求的。

**Comment by troyeguo** [comment]
麻烦您提供一下电子书文件

**Comment by sstiger1230** [comment]
[《庆余年》（精校版全本）作者：猫腻.zip](https://github.com/troyeguo/koodo-reader/files/9856933/default.zip)

**Comment by troyeguo** [comment]
我在windows10上测试，可以正常展示，请检查您的操作系统的编码格式设置。
