### ISSUE TITLE
打开epub时记忆上次阅读进度错误

### ISSUE THREAD

**Issue by winter110** [koodo-reader/koodo-reader#628]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

其他 Linux 发行版

### Koodo Reader 版本

1.4.9开发版

### 我遇到的问题

打开一个epub后，进行翻页，之后关闭程序，再打开刚才的文件，记录的页数不是关闭之前的最新阅读的页数，而是更早之前阅读的某一页。

**Comment by SWZi66** [comment]
一样的问题
