### ISSUE TITLE
webdav备份到坚果云失败

### ISSUE THREAD

**Issue by ZhouSong0** [koodo-reader/koodo-reader#651]
### I've already installed the latest developer version of Koodo Reader, this problem still exsits

- [X] Yes

### There are no similar issues on the issue list

- [X] Yes

### I've already read the document, still can't solve it.

- [X] Yes

### Operating system or browser

Windows 11

### App Version

1.4.2

### Bug Detail

在通过坚果云的webdav备份时失败，会一直停留在请稍后界面。账号信息填写无误，但是依旧无法备份，请求解决办法

![quicker_81818a09-da11-46c5-a850-ec4206d48036.png](https://s2.loli.net/2022/12/07/78taV6RvomrMAHX.png)

![quicker_0bf15f45-91bf-4cb6-9c3f-209491ac4bcc.png](https://s2.loli.net/2022/12/07/LXw1jmGHVPaCskf.png)

**Comment by troyeguo** [comment]
会不会是备份文件太大，再加上网络不稳定。

**Comment by Steven7920** [comment]
并没有，我只是导入了两本书试了下备份功能，发现无法备份。网络应该也没问题吧。而且我试了一下用DropBox备份，竟然可以备份成功，但是用坚果云就会出现上面所描述的情况，软件版本是1.4.2

**Comment by Steven7920** [comment]
哇，我发现问题所在了，我在坚果云看webdav服务器地址是https://dav.jianguoyun.com/dav/ 但是在koodo中填写webdav地址要填写http://dav.jianguoyun.com/dav/ 才能够备份成功。。。

**Comment by troyeguo** [comment]
建议先升级到1.5.0，我这里用https的地址是没有问题的

**Comment by Steven7920** [comment]
<img width="809" alt="优效截图20221212102440" src="https://user-images.githubusercontent.com/68318446/206947791-a35d8da7-399d-4528-95de-7e9b2dd0998a.png">
<img width="685" alt="优效截图20221212102604" src="https://user-images.githubusercontent.com/68318446/206947796-be600769-d31a-4562-8b68-f56fac0f3952.png">
用https的时候会出现网络错误，但是我网络应该没问题啊

**Comment by Steven7920** [comment]
<img width="512" alt="优效截图20221212103306" src="https://user-images.githubusercontent.com/68318446/206948525-8e9647ed-30d1-4ec3-8a7a-b76558c5cf34.png">
这是使用http时，可以备份，但是恢复的时候就会出错。。。

**Comment by sharecycle** [comment]
> 会不会是备份文件太大，再加上网络不稳定。

作者大大，我也碰到了这个备份失败的问题，我导入的书有点多，大概130本左右，而且备份到本地/WebDav我都试了都是失败。后续有没有可能解决这个因为文件过大备份失败的问题啊

**Comment by JiangLongLiu** [comment]
问题解决了吗，我也遇到了这个问题

**Comment by JiangLongLiu** [comment]
> > 问题解决了吗，我也遇到了这个问题
> 
> 最新开发版1.8.1上也存在问题吗？我这边测试正常

我就是1.8.1版本，存在问题
