### ISSUE TITLE
epub电子书选中文字时会触发翻页，导致无法指定划线

### ISSUE THREAD

**Issue by Ajaxlover** [koodo-reader/koodo-reader#661]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Chrome 及其他 Chromium 浏览器(包括 Edge 和所有国产浏览器)

### Koodo Reader 版本

1.4.9

### 我遇到的问题

展示epub电子书，当我想选中一段文字标注划线时，发现它会默认触发翻页（向左选中会翻页到上一页，向右选中会翻页到下一页）

**Comment by troyeguo** [comment]
请检查以下设置里的触控屏模式是否开启，开启了的话就关掉

**Comment by Ajaxlover** [comment]
> 请检查以下设置里的触控屏模式是否开启，开启了的话就关掉
哦哦哦，用户的锅
