### ISSUE TITLE
关于翻译功能: 建议添加"源语言"的选择

### ISSUE THREAD

**Issue by chunis** [koodo-reader/koodo-reader#663]
### 我已经阅读了 Koodo Reader 的开发计划，没有找到类似的需求

- [X] Yes

### 这个 issue 没有同时提多个需求.

- [X] Yes

### 简单介绍

关于翻译功能, 建议添加"源语言"的选择

### 细节描述

西方各语言存在很多形似的单词, 所以依靠翻译引擎来猜测源语言有时候并不准确. 所以是否可以添加一个"源语言"选择框, 来指定特定的语言或者"自动选择"? Thanks.

**Comment by troyeguo** [comment]
感谢您的建议，会考虑增加这个功能的
