### ISSUE TITLE
书架图书丢失

### ISSUE THREAD

**Issue by qlmlove** [koodo-reader/koodo-reader#664]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 11

### Koodo Reader 版本

1.5.0开发板

### 我遇到的问题

曾经导入过的书籍全部从书架上消失了，但是设置里的那个存储目录里还有内容，不知道怎么恢复书架

### 截图或录像(可选的)

![image](https://user-images.githubusercontent.com/37925929/207743721-11361039-a7ff-49c2-847b-8c43884f4a03.png)
![image](https://user-images.githubusercontent.com/37925929/207743798-6cf9e07a-826e-4025-be96-594c2299df22.png)

**Comment by troyeguo** [comment]
您之前有备份过吗？如果没有的话，就无法找回了

**Comment by troyeguo** [comment]
回收站还有吗，如果没有的话就没办法了

**Comment by AnnAny1** [comment]
> 回收站还有吗，如果没有的话就没办法了

这个问题1.5.1与1.5.2都存在。会清空书架，但是缓存是存在的。还有就是云端备份不了恢复不了，一直加载。本地备份也无法进行选择。（之前一直可以，这几个版本出问题后备份恢复操作发现不可行）

**Comment by troyeguo** [comment]
> > 回收站还有吗，如果没有的话就没办法了
> 
> 这个问题1.5.1与1.5.2都存在。会清空书架，但是缓存是存在的。还有就是云端备份不了恢复不了，一直加载。本地备份也无法进行选择。（之前一直可以，这几个版本出问题后备份恢复操作发现不可行）

麻烦您提供一下备份文件，用于调试

**Comment by kingski233** [comment]
我也遇到类似的问题，请问后来还能解决吗
