### ISSUE TITLE
大epub无法保存阅读进度

### ISSUE THREAD

**Issue by loadOverload** [koodo-reader/koodo-reader#670]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10 及以下

### Koodo Reader 版本

1.5.1

### 我遇到的问题

在使用最新版本阅读一个epub文件时，发现翻页后页码和阅读进度无反应，退出重进后原来的阅读进度就没了

### 截图或录像(可选的)

![image](https://user-images.githubusercontent.com/105843317/208989583-c48a321e-9681-43ff-8004-83a81f3b026a.png)

### 图书文件(可选的)

[卡拉马佐夫兄弟（套装上下册） (陀思妥耶夫斯基文集) ( etc.) (z-lib.org).zip](https://github.com/troyeguo/koodo-reader/files/10280644/etc.z-lib.org.zip)

**Comment by MoMeiShengShuai** [comment]
我也是，时不时卡一下
