### ISSUE TITLE
设置背景颜色无反应

### ISSUE THREAD

**Issue by Pahkho** [koodo-reader/koodo-reader#674]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10 及以下

### Koodo Reader 版本

1.5.1 最新稳定版

### 我遇到的问题

首次设置 背景色:绿色 打开不使用仿真背景
以后无论怎么设置背景色 都不能设置为绿色 
不能复现这个bug可以试多几次  刚刚重新试了一次又复现了
目前不知道其它的选项会不会也造成这个原因

### 截图或录像(可选的)

![image](https://user-images.githubusercontent.com/52782346/209620712-d91c60ba-4e8a-4dc0-bb0c-a8a06fa1473d.png)
使用改选项 设置绿色背景 关闭阅读页面 再次打开应该可以复现

**Comment by troyeguo** [comment]
不好意思，我这里无法复现

**Comment by Pahkho** [comment]
> 不好意思，我这里无法复现

Version:1.5.1最新稳定版
1.打开图书
2.设置背景颜色:绿色
3.勾选->不使用仿真背景
4.关闭图书,重新打开图书
先前设置的背景颜色(绿色不生效),设置其它背景颜色之后重新打开图书也不会生效
解决方法:不勾选->不使用仿真背景即可
