### ISSUE TITLE
建议增加单页翻页功能

### ISSUE THREAD

**Issue by wutong233** [koodo-reader/koodo-reader#694]
### 我已经阅读了 Koodo Reader 的开发计划，没有找到类似的需求

- [X] Yes

### 这个 issue 没有同时提多个需求.

- [X] Yes

### 简单介绍

可以极大方便截图中右下角这种代码一个屏幕内看不全的问题。
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/35332983/211511082-17e583ad-0ec7-4b8b-85a5-ecde17b3b13e.png">

### 细节描述

Word的阅读视图就有这个功能，左右各一页，翻页时仅滚动一页（右边那页移动到左边）。

**Comment by troyeguo** [comment]
感谢您的建议，会考虑的。您可以暂时使用滚动模式
