### ISSUE TITLE
打开书籍后，直接加入书库

### ISSUE THREAD

**Issue by xiliangm** [koodo-reader/koodo-reader#735]
### 我已经阅读了 Koodo Reader 的开发计划，没有找到类似的需求

- [X] Yes

### 这个 issue 没有同时提多个需求.

- [X] Yes

### 简单介绍

打开书籍后，可以直接添加到书库，不用在主界面添加

### 细节描述

有时会先打开一本epub，查看下内容是否合适，再决定是不是放进书库。
目前似乎不能直接把打开的书籍添加到书库，还需要回去主界面操作。
希望可以添加这个小功能。

**Comment by troyeguo** [comment]
目前默认就是会加入的，请检查设置中打开图书但不加入书库选项是否开启
