### ISSUE TITLE
无法强制显示自定义字体了

### ISSUE THREAD

**Issue by backdreamliu** [koodo-reader/koodo-reader#848]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10 及以下

### Koodo Reader 版本

1.5.6

### 我遇到的问题

1.5.5版本可以显示我选择的字体，但有我之前反馈的部分书籍不能导入问题。

今天更新了新版，发现只有目录能显示自定义字体，但正文没法显示。

见截图。

另外，行间距也无法调整。

### 截图或录像(可选的)

![2023-06-25_165512](https://github.com/troyeguo/koodo-reader/assets/74800920/a14a8b73-7ef5-469e-a9e8-d22b7256f84d)
![2023-06-25_165551](https://github.com/troyeguo/koodo-reader/assets/74800920/2c1cfeef-b5bc-46cf-b257-f468eeac9720)

**Comment by troyeguo** [comment]
图书目录没有指定显示的字体，所以可以覆盖，而正文指定了，所以没法覆盖。后续会考虑增加一个选项，是否强制覆盖书中字体。

**Comment by backdreamliu** [comment]
感谢回复。建议在字体里面加一个选项，使用书籍指定字体。然后选其他字体默认进行强制显示自定义字体，或者仅正文使用强制字体。
