### ISSUE TITLE
希望增加滚轮翻页功能

### ISSUE THREAD

**Issue by GarfiledXu** [koodo-reader/koodo-reader#881]
### 我已经阅读了 Koodo Reader 的开发计划，没有找到类似的需求

- [X] Yes

### 这个 issue 没有同时提多个需求.

- [X] Yes

### 简单介绍

似乎在文本页面完整嵌合在界面中时，不能像其他软件一样滚轮进行翻页，只能通过上下键
其次页面的编排控制非常僵硬，缩放比例只能10%为单位，大部分pdf能实现轻松的双页面正中心的完全展示，这个软件很难做到，并且没法只单独展示两个页面，并且书籍模式下整页翻，只能通过左上角的图标点击进行，如果有对应快捷键也勉强能接受

### 细节描述

似乎在文本页面完整嵌合在界面中时，不能像其他软件一样滚轮进行翻页，只能通过上下键
其次页面的编排控制非常僵硬，缩放比例只能10%为单位，大部分pdf能实现轻松的双页面正中心的完全展示，这个软件很难做到，并且没法只单独展示两个页面，并且书籍模式下整页翻，只能通过左上角的图标点击进行，如果有对应快捷键也勉强能接受

**Comment by SymmetryandConservation** [comment]
+1,一章结束后滚动模式无法翻页

**Comment by troyeguo** [comment]
pdf阅读器的功能建议请前往pdf.js页面反馈，我们只会从他们那里更新代码
https://github.com/mozilla/pdf.js/
