### ISSUE TITLE
图片脚注与文字/图片重叠、图片分割到两页中、滚动阅读模式章节显示不全

### ISSUE THREAD

**Issue by CKlimeths** [koodo-reader/koodo-reader#882]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10 及以下

### Koodo Reader 版本

1.5.6

### 我遇到的问题

1. 图片下的脚注会与接下来的文字或是图片发生重叠。

2. 太长的图片被切割成两块分别显示在两页中。
类似提到图片截断的 issue：#845、#459，但目前 releases/latest - 1.5.6 中该问题依然存在。

3. 滚动模式下有时候会出现已经滑到最底部了，但最后一些内容没有显示的问题。

此外，补充一个查看图片功能的改进建议：希望在点击图片查看大图的模式中，提供一个滚轮缩放，鼠标按住拖动的看图方式。

### 截图或录像(可选的)

图片脚注与文字/图片重叠、图片分割到两页中
![image](https://github.com/troyeguo/koodo-reader/assets/86591721/18c17d47-8310-47e9-8054-b3ee1f63f395)
![image](https://github.com/troyeguo/koodo-reader/assets/86591721/ba656c05-71e6-4a72-9334-608a4d08ca63)

滚动模式已经滑到最底部了
![image](https://github.com/troyeguo/koodo-reader/assets/86591721/33325ba1-429f-406f-8c3d-643f3af3c7b0)
切到双叶模式能看到最后一个图片后面其实还有内容
![image](https://github.com/troyeguo/koodo-reader/assets/86591721/24a28bcf-fe77-4727-8df9-d0cfb4fdb1c9)

### 图书文件(可选的)

链接: https://pan.baidu.com/s/1A7fgUNYqBEgQAwyTayPmxA?pwd=cem9 提取码: cem9 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by troyeguo** [comment]
文件太大，请不要用百度网盘分享，可以把文件压缩为zip格式，然后直接拖拽到github输入框

**Comment by troyeguo** [comment]
图片分割到两页中和滚动阅读模式章节显示不全已修复，请升级至1.5.7
