### ISSUE TITLE
设置不显示设计按钮，高亮也是黑色，不显示彩色

### ISSUE THREAD

**Issue by yixuejun** [koodo-reader/koodo-reader#896]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 11

### Koodo Reader 版本

1.5.7

### 我遇到的问题

1. 安装1.5.1，设置页面，不显示相关设置开关，升级到1.5.6，1.5.7还是一样问题
2. 高亮工具也都是黑色界面，选择高亮后也不能正确选择颜色

### 截图或录像(可选的)

![image](https://github.com/troyeguo/koodo-reader/assets/53308952/95ef249e-b9cb-4663-98da-d9261b434b1e)

![image](https://github.com/troyeguo/koodo-reader/assets/53308952/fe258fe4-5e4b-41ec-aaff-0a01159340fe)

**Comment by troyeguo** [comment]
您的屏幕明显看起来发黄，这是什么软件或者系统设置导致的吗？
