### ISSUE TITLE
二级目录无法跳转

### ISSUE THREAD

**Issue by louiejordan** [koodo-reader/koodo-reader#897]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 11

### Koodo Reader 版本

1.5.7

### 我遇到的问题

不得不说相比calibre来说，打开文件的速度是真的快，但是有个小问题，就是二级目录无法跳转，epub、azw3和mobi都是一样的问题

**Comment by troyeguo** [comment]
我这里测试没有问题，麻烦您提供一下电子书文件

**Comment by QPYIDRWIMG** [comment]
通过左侧目录跳转到`黄帝内经（第二册）`的章节，只有`封面`和`目录`能跳转，其他章节不能跳转。
[Uploading 黄帝内经（精注全译）（全六册）.zip…]()
![image](https://github.com/koodo-reader/koodo-reader/assets/115329998/2e930398-a11a-4880-90f7-eb21524fd050)

**Comment by QPYIDRWIMG** [comment]
> 通过左侧目录跳转到`黄帝内经（第二册）`的章节，只有`封面`和`目录`能跳转，其他章节不能跳转。 ![image](https://private-user-images.githubusercontent.com/115329998/289759780-2e930398-a11a-4880-90f7-eb21524fd050.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNjE2NDksIm5iZiI6MTcwMjM2MTM0OSwicGF0aCI6Ii8xMTUzMjk5OTgvMjg5NzU5NzgwLTJlOTMwMzk4LWExMWEtNDg4MC05MGY3LWViMjE1MjRmZDA1MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMlQwNjA5MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMjNjZTZhMTVmNGQwZTU5YThhZjQ2ZjM1YTE0ODdlNDE4OTVmYzVhZGI4NjQxMTQyMzI1OWI0ZWY2MDlkMWY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OAn6RbES698nxzqWhg0Bpgyl4N6H3lF05ZHw2oWYAZU)
> 
> 电子书文件： [黄帝内经（精注全译）（全六册）.zip](https://github.com/koodo-reader/koodo-reader/files/13644331/default.zip)

除此之外，点击`黄帝内经（第二册）`下，`目录`章节内，章节的名称，没有反应。
