### ISSUE TITLE
Hide the scrollbar since the pdf reader already has a scroll bar. 

### ISSUE THREAD

**Issue by Y-jiji** [koodo-reader/koodo-reader#898]
### I've read Koodo Reader's roadmap, there is no similar feature.

- [X] Yes

### This issue only requests one feature.

- [X] Yes

### Brief Introduction

Hide the scrollbar since the pdf reader already has a scroll bar. 

### Details

Hide the scrollbar since the pdf reader already has a scroll bar. 
<img width="1281" alt="image" src="https://github.com/troyeguo/koodo-reader/assets/71013200/10176fd8-610a-459a-bb64-69e5c9abd181">

**Comment by troyeguo** [comment]
Thanks for the advice, we will fix it in the next update.
