### ISSUE TITLE
Mac(m1)安装问题，M1/M2运行已安装软件提示“XXX 已损坏解决办法（原帮助文档中的方法在新的macos中不适用）

### ISSUE THREAD

**Issue by redface999** [koodo-reader/koodo-reader#899]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

macOS 10 及以下

### Koodo Reader 版本

1.5.1

### 我遇到的问题

macOS 13  解决问题的链接：https://osx.cx/m1-m2-install-prompt-xxx-corrupt.html

### 截图或录像(可选的)

![截屏2023-08-01 21 45 36](https://github.com/troyeguo/koodo-reader/assets/581131/5a6d7598-ee42-4e50-a796-e6d954222341)

**Comment by troyeguo** [comment]
感谢您的反馈，我们会尽快更新文档的

**Comment by bolechen** [comment]
文档中的方法无效，正确的作法是


```
xattr -c /Applications/Koodo\ Reader.app
```
