### ISSUE TITLE
按钮图标未对齐

### ISSUE THREAD

**Issue by Puiching-Memory** [koodo-reader/koodo-reader#903]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 11

### Koodo Reader 版本

1.5.7

### 我遇到的问题

这三个按钮间隔不同，而且垂直也没有对齐

### 截图或录像(可选的)

<img width="132" alt="屏幕截图 2023-08-05 142855" src="https://github.com/troyeguo/koodo-reader/assets/83509039/6b25c6e7-1626-4d67-94b9-952fc3941857">
<img width="160" alt="屏幕截图 2023-08-05 142851" src="https://github.com/troyeguo/koodo-reader/assets/83509039/fbc3ab03-fffe-4c62-a79b-52f46e2f6e42">

**Comment by troyeguo** [comment]
感谢您的反馈，会在下个版本修复的

**Comment by troyeguo** [comment]
请升级1.6.0版
