### ISSUE TITLE
重叠渲染

### ISSUE THREAD

**Issue by Puiching-Memory** [koodo-reader/koodo-reader#905]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 11

### Koodo Reader 版本

1.5.7

### 我遇到的问题

书本图片区域会有几个像素入侵到功能栏，导致重叠渲染

系统图形设置：缩放150%/分辨率2560x1600

版本	Windows 11 家庭中文版
版本	22H2
安装日期	‎2023/‎6/‎12
操作系统版本	22621.2070
序列号	YX05GZ71
体验	Windows Feature Experience Pack 1000.22659.1000.0

### 截图或录像(可选的)

<img width="254" alt="屏幕截图 2023-08-06 144818" src="https://github.com/troyeguo/koodo-reader/assets/83509039/23aae16f-4b5a-49e5-95d1-01826e685300">

**Comment by troyeguo** [comment]
感谢您的反馈，会在下个版本修复的。
