### ISSUE TITLE
窗口大小调整后，epub阅读器的排版行为异常

### ISSUE THREAD

**Issue by Puiching-Memory** [koodo-reader/koodo-reader#911]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 11

### Koodo Reader 版本

1.5.7

### 我遇到的问题

该问题表现为页面内容不再自动适应窗口大小变化，或者使用了错误的排版处理方法

### 截图或录像(可选的)

https://github.com/troyeguo/koodo-reader/assets/83509039/dd5d10ea-70ba-4742-b142-14b4f003783b

https://github.com/troyeguo/koodo-reader/assets/83509039/aaf61679-8db5-4bd2-98e9-7904110bd980

**Comment by troyeguo** [comment]
感谢您的反馈，会在下个版本修复
