### ISSUE TITLE
导入pdf失败

### ISSUE THREAD

**Issue by leafmoes** [koodo-reader/koodo-reader#916]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 11

### Koodo Reader 版本

1.5.7

### 我遇到的问题

导入pdf失败，界面无反应，开发者控制台提示如下：
Deprecated API usage: No "GlobalWorkerOptions.workerSrc" specified.
display_utils.js:556 Deprecated API usage: No "GlobalWorkerOptions.workerSrc" specified.
util.js:366 Warning: Error during font loading: The CMap "baseUrl" parameter must be specified, ensure that the "cMapUrl" and "cMapPacked" API parameters are provided.
bookUtil.tsx:404 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'preCache')
    at bookUtil.tsx:404
    at p (regeneratorRuntime.js:44)
    at Generator.<anonymous> (regeneratorRuntime.js:125)
    at Generator.next (regeneratorRuntime.js:69)
    at r (asyncToGenerator.js:3)
    at s (asyncToGenerator.js:22)

### 截图或录像(可选的)

![image](https://github.com/troyeguo/koodo-reader/assets/44945631/88e5245a-03a3-4656-863c-01ece6da7acb)

### 图书文件(可选的)

[On_Java_中文版_基础卷_(Bruce_Eckel)_leafmoes修正.pdf](https://github.com/troyeguo/koodo-reader/files/12380216/On_Java_._._.Bruce_Eckel._leafmoes.pdf)

**Comment by leafmoes** [comment]
https://reader.960960.xyz/#/manager/home
网页端可以正常导入

**Comment by leafmoes** [comment]
Win端不知道为什么不可以导入成功

**Comment by leafmoes** [comment]
经测试1.5.1并没有这个问题出现

**Comment by zhang-stephen** [comment]
> Win端不知道为什么不可以导入成功

我也遇到这个问题，但是仅在绿色版上出现。安装版没有问题

**Comment by leafmoes** [comment]
> 

我使用Scoop管理我的软件

**Comment by leafmoes** [comment]
> > Win端不知道为什么不可以导入成功
> 
> 我也遇到这个问题，但是仅在绿色版上出现。安装版没有问题


我使用Scoop管理我的软件
