### ISSUE TITLE
文档属性中的作者信息和书架不一致

### ISSUE THREAD

**Issue by zhang-stephen** [koodo-reader/koodo-reader#920]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 11

### Koodo Reader 版本

1.5.7

### 我遇到的问题

将附件中的pdf导入，在书架上的作者信息显示为佚名：

![image](https://github.com/troyeguo/koodo-reader/assets/17326718/795713e7-e7d6-4e08-9e5e-f7429626adb4)

但是在打开图书后，文档属性中却可以看到真正的作者

![image](https://github.com/troyeguo/koodo-reader/assets/17326718/313a13b8-2f05-45b7-adc0-722f077b1aab)

P.S. 文件名为什么是document.pdf?

### 图书文件(可选的)

文件太大，无法上传……

**Comment by troyeguo** [comment]
感谢您的反馈，会在后续版本修复的

**Comment by troyeguo** [comment]
请升级1.6.0版
