### ISSUE TITLE
看txt小说，双页有问题，本章最后一页一定要排到右侧。会把上页的右侧拉回第二页的左侧。

### ISSUE THREAD

**Issue by theking988** [koodo-reader/koodo-reader#922]
### 我已经阅读了 Koodo Reader 的开发计划，没有找到类似的需求

- [X] Yes

### 这个 issue 没有同时提多个需求.

- [X] Yes

### 简单介绍

例如：本章小说最后文字应该显示在左侧。右侧为空白。或是下章的开始排在右侧也好。但是现在的版为了让本章最后文字显示在右侧。硬是把上页已看完的文字显示在本页的左侧。造成我经常看的时候发现左侧是看过的。右侧才是新的。非常影响观感

### 细节描述

电脑是MacBook。
例如：本章小说最后文字应该显示在左侧。右侧为空白。或是下章的开始排在右侧也好。但是现在的版为了让本章最后文字显示在右侧。硬是把上页已看完的文字显示在本页的左侧。造成我经常看的时候发现左侧是看过的。右侧才是新的。非常影响观感。如果可以的话。希望可以把右侧空出来或是直接连着下一章。谢谢。软件非常棒。

**Comment by troyeguo** [comment]
这个问题已经在最新的1.5.7中修复了
