### ISSUE TITLE
There is a problem with double-page support for txt typesetting

### ISSUE THREAD

**Issue by theking988** [koodo-reader/koodo-reader#923]
### I've read Koodo Reader's roadmap, there is no similar feature.

- [X] Yes

### This issue only requests one feature.

- [X] Yes

### Brief Introduction

There is a problem with double-page support for txt typesetting.
When reading the chapter, if the last page is not on the right. By default, the previous page will be displayed back (on the left page). Very unfriendly to novel reading. Please modify it. There is not enough text in this chapter, and the right side can be left blank.

### Details

Mac OS Big Sur
There is a problem with double-page support for txt typesetting.
When reading the chapter, if the last page is not on the right. By default, the previous page will be displayed back (on the left page). Very unfriendly to novel reading. Please modify it. There is not enough text in this chapter, and the right side can be left blank.

**Comment by troyeguo** [comment]
This issue has been resolved in the latest 1.5.7 version.

**Comment by theking988** [comment]
very thanks. i check
