### ISSUE TITLE
希望章节栏，大章可以折叠

### ISSUE THREAD

**Issue by 7777777lai** [koodo-reader/koodo-reader#926]
### 我已经阅读了 Koodo Reader 的开发计划，没有找到类似的需求

- [X] Yes

### 这个 issue 没有同时提多个需求.

- [X] Yes

### 简单介绍

希望章节栏，大章可以折叠

### 细节描述

希望章节栏，大章可以折叠。
这样可以把读过的章节折起来。

![QQ截图20230827040543](https://github.com/troyeguo/koodo-reader/assets/46947901/4461ca8e-77a0-48ff-95c4-08288ce57092)

**Comment by troyeguo** [comment]
感谢您的建议，会在下个版本支持的

**Comment by nothingandignorant** [comment]
> 感谢您的建议，会在下个版本支持的

我等到了1.6.1版本还没看到这个功能🤣

**Comment by troyeguo** [comment]
请在设置里关闭默认展开所有目录
