### ISSUE TITLE
epub文件的数学公式渲染在升级后工作不正常

### ISSUE THREAD

**Issue by dzx-dzx** [koodo-reader/koodo-reader#942]
### 我已经从 Github Release 安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 11

### Koodo Reader 版本

1.5.7

### 我遇到的问题

打开附件的epub后，在第三章的第一个公式显示不正常。该公式在1.5.1正常

### 截图或录像(可选的)

当前版本1.5.7:
![image](https://github.com/troyeguo/koodo-reader/assets/31068367/d1a7d106-89c5-4ce4-a880-ebcf29b17b15)
1.5.1:
![image](https://github.com/troyeguo/koodo-reader/assets/31068367/95454be9-004f-4273-bf49-057083a8c73c)

### 图书文件(可选的)

[Richard W. Hamming - The Art Of Probability-CRC Press (2018)(1).zip](https://github.com/troyeguo/koodo-reader/files/12585747/Richard.W.Hamming.-.The.Art.Of.Probability-CRC.Press.2018.1.zip)

**Comment by troyeguo** [comment]
感谢您的反馈，最新开发版更换了epub解析引擎，这个问题会在后续版本修复的

**Comment by dzx-dzx** [comment]
感谢！

**Comment by ctfysh** [comment]
在ubuntu系统上最新版1.7.2也有类似的问题，网页版正常。
