### ISSUE TITLE
导入大文件txt文档时卡顿

### ISSUE THREAD

**Issue by LongWenHu** [koodo-reader/koodo-reader#945]
### 我已经阅读了 Koodo Reader 的开发计划，没有找到类似的需求

- [X] Yes

### 这个 issue 没有同时提多个需求.

- [X] Yes

### 简单介绍

我导入了一个17.1 MB的TXT文本。
界面卡了一段时间才反应过来，
后续点右上角图标，或者点击翻页也会有卡顿的体验。

### 细节描述

测试文件：xxx.txt
文件大小：17.1 MB
测试电脑性能：
    处理器：AMD Ryzen 7 4800H with Radeon Graphics            2.90 GHz
    内存：16G
    系统版本：Windows 11 专业版/22H2/22621.1848

**Comment by troyeguo** [comment]
感谢您的反馈，导入的问题会在后续版本优化的。翻页卡顿有可能是分章算法的问题，麻烦您提供一下电子书文件，用于测试
