### ISSUE TITLE
[1.5.9] 重启不能记住上次阅读准确位置，Bookmark也不能准确定位，页面显示文字重叠

### ISSUE THREAD

**Issue by thinkfan** [koodo-reader/koodo-reader#951]
### 我已经从 Github Release 安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10 及以下

### Koodo Reader 版本

1.5.9

### 我遇到的问题

1. 重启不能记住上次阅读**准确**位置
2. Bookmark也不能准确定位
3. 页面显示文字重叠（见下面截图，图书文件Chapter18，连续浏览模式，其他Chapter也有类似问题）

### 截图或录像(可选的)

![BugSnapshot1](https://github.com/troyeguo/koodo-reader/assets/1967862/b8961d8a-1a0a-4583-baad-9dc693c67957)

### 图书文件(可选的)

链接：https://pan.baidu.com/s/1q4W4asWAdv2WvivmO1qxrA 
提取码：vxv2

**Comment by thinkfan** [comment]
koodo 是我目前发现的最好的 epub reader：首先是免费开源无广告！显示效果简洁优美，书页的立体感非常喜欢；个性化设置比较全面（比如设置护眼色、宽度、高度等）；可以正常显示 Table（看文献蛮重要的）。有待完善的地方：记不准上次的阅读位置，有点麻烦；某些文字之间、文字与图片或表格会发生重叠，也影响阅读效果。如果这些能修复就更完美了。对了，PDF的显示跟SumatraPDF还有点差距，希望能借鉴提升。总体还是很有潜力的阅读器，加油！

**Comment by troyeguo** [comment]
重叠的问题会在后续版本修复的，我这里没法复现定位不准的问题。您可以提供一下操作录像吗

**Comment by thinkfan** [comment]
操作录像请从下面链接下载（视频中，软件能记住我阅读到了Chapter 16，但不能记住该章节中的准确位置，用书签也不行）：

链接：https://pan.baidu.com/s/14cxhqfYLr335NuxJjytKsQ 
提取码：x863

**Comment by troyeguo** [comment]
这个问题和滚动模式有关，会在下个版本修复的

**Comment by thinkfan** [comment]
发现一个新的问题：脚注、图片引用不能来回导航，比如 Chapter 15 第一页中的脚注 1 和 Figure 15.1

**Comment by troyeguo** [comment]
> 发现一个新的问题：脚注、图片引用不能来回导航，比如 Chapter 15 第一页中的脚注 1 和 Figure 15.1

感谢您的反馈，会在下个版本修复的

**Comment by troyeguo** [comment]
请升级1.6.0版
