### ISSUE TITLE
epub目录跳转 bug

### ISSUE THREAD

**Issue by holmebin** [koodo-reader/koodo-reader#954]
### 我已经从 Github Release 安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10 及以下

### Koodo Reader 版本

1.5.9

### 我遇到的问题

在epub目录toc.ncx文件中， 采用页面路径的标签  content src="1/titlepage.xhtml"可以正确跳转， 而采用页面路径+#id的方式   content src="1/index_split_000.html#p34"不能正确跳转

### 截图或录像(可选的)

无

### 图书文件(可选的)

无

**Comment by troyeguo** [comment]
麻烦提供一下电子书文件

**Comment by holmebin** [comment]
因为工作的关系，曾面对无数好友呼叫不能回应，最痛苦的事莫过于此！  如果给我一次机会 ，我要说一句话：不是我不理你，只是时间难以抗拒！！  如果一定要给这句话加个期限，我希望是：再等一会儿！！！

**Comment by holmebin** [comment]
[Harry Potter Series Book 1-7.zip](https://github.com/troyeguo/koodo-reader/files/13050097/Harry.Potter.Series.Book.1-7.zip)
电子书文件

**Comment by troyeguo** [comment]
我这边测试，跳转是正常的。书中有隐藏的a标签，和目录中的id匹配
![image](https://github.com/troyeguo/koodo-reader/assets/13820674/6323ab2c-8582-409d-885f-a3dac9839abe)

**Comment by holmebin** [comment]
因为工作的关系，曾面对无数好友呼叫不能回应，最痛苦的事莫过于此！  如果给我一次机会 ，我要说一句话：不是我不理你，只是时间难以抗拒！！  如果一定要给这句话加个期限，我希望是：再等一会儿！！！

**Comment by holmebin** [comment]
![Snipaste_2023-10-28_10-19-10](https://github.com/troyeguo/koodo-reader/assets/49544221/c84f24b0-47e7-4662-b137-ee8fb8389d90)
![Snipaste_2023-10-28_10-19-35](https://github.com/troyeguo/koodo-reader/assets/49544221/cb6cecaf-1823-49bc-8063-ff81b441d778)
这两个就不能正常跳转，展示的是封面，因为他们是采用页面路径+#id的方式 content src="1/index_split_000.html#p34"

**Comment by holmebin** [comment]
![image](https://github.com/troyeguo/koodo-reader/assets/49544221/cb652018-7525-4b56-9b75-560aba9e94ba)

**Comment by troyeguo** [comment]
感谢您的反馈，会在下个版本修复这个问题的

**Comment by troyeguo** [comment]
请升级1.6.0版
