### ISSUE TITLE
开启“自动预缓存导入的图书”后，很多pdf无法导入

### ISSUE THREAD

**Issue by Janus1984** [koodo-reader/koodo-reader#956]
### 我已经从 Github Release 安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Ubuntu

### Koodo Reader 版本

1.5.9

### 我遇到的问题

在设置中开启“自动预缓存导入的图书”后，很多pdf都无法导入。关闭这个选项后就正常。

**Comment by troyeguo** [comment]
感谢您的反馈，会在下个版本修复的

**Comment by troyeguo** [comment]
请升级1.6.0版
