### ISSUE TITLE
部分txt文件不能正常打开，会乱码

### ISSUE THREAD

**Issue by WHeathcliff** [koodo-reader/koodo-reader#961]
### 我已经从 Github Release 安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 11

### Koodo Reader 版本

1.5.9开发版

### 我遇到的问题

部分txt文件无法正常打开，会长时间白屏，最后乱码，重装软件后该问题依然存在。

### 截图或录像(可选的)

<img width="779" alt="Snipaste_2023-10-13_09-20-01" src="https://github.com/troyeguo/koodo-reader/assets/67552998/736d1a55-709e-47f0-940a-9f86d812424a">
<img width="635" alt="Snipaste_2023-10-13_09-20-44" src="https://github.com/troyeguo/koodo-reader/assets/67552998/8ee49e78-75ba-4713-806b-ab1a73fd1f4a">

### 图书文件(可选的)

[《我在1982有个家》作者：全金属弹壳.zip](https://github.com/troyeguo/koodo-reader/files/12888486/1982.zip)

**Comment by troyeguo** [comment]
感谢您的反馈，会在下个版本修复的

**Comment by troyeguo** [comment]
请升级1.6.0版
