### ISSUE TITLE
鼠标不能选中文字

### ISSUE THREAD

**Issue by silentismylife** [koodo-reader/koodo-reader#965]
### I've already installed the latest developer version of Koodo Reader from Github Release, this problem still exsits

- [X] Yes

### There are no similar issues on the issue list

- [X] Yes

### I've already read the document, still can't solve it.

- [X] Yes

### Operating system or browser

Windows 10 and below

### App Version

版本	Windows 10 家庭中文版 版本号	22H2 安装日期	‎2022/‎10/‎12 操作系统内部版本	19045.3448 体验	Windows Feature Experience Pack 1000.19044.1000.0

### Bug Detail

equb文件使用鼠标选中文字时，会自己返回上一页，而且内置翻译不能使用

### Screenshots (Optional)

![11](https://github.com/troyeguo/koodo-reader/assets/144451746/17bb002d-170a-4a78-967f-d2eba72b0beb)

**Comment by troyeguo** [comment]
请升级1.6.0版
