### ISSUE TITLE
使用1.5.9版本打不开md文件，一直显示loading

### ISSUE THREAD

**Issue by LuckyHangMei** [koodo-reader/koodo-reader#968]
### I've already installed the latest developer version of Koodo Reader from Github Release, this problem still exsits

- [X] Yes

### There are no similar issues on the issue list

- [X] Yes

### I've already read the document, still can't solve it.

- [X] Yes

### Operating system or browser

Windows 10 and below

### App Version

1.5.9

### Bug Detail

用Koodo-Reader-1.5.9-x64-Win版本打开我本地使用Typora编写的md文件打不开

**Comment by troyeguo** [comment]
感谢您的反馈，会在下个版本修复的

**Comment by troyeguo** [comment]
请升级1.6.0版
