### ISSUE TITLE
双栏下，要跨栏复制时无法看到复制选项

### ISSUE THREAD

**Issue by qiangweihewu** [koodo-reader/koodo-reader#971]
### 我已经从 Github Release 安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 11

### Koodo Reader 版本

1.5.9 开发版

### 我遇到的问题

如题，一旦跨栏，则有复制选项的弹窗在界面顶部，无法看到

### 截图或录像(可选的)
![image](https://github.com/troyeguo/koodo-reader/assets/91766951/81d41111-953d-43f1-9b3f-bd1968b5c00e)

![image](https://github.com/troyeguo/koodo-reader/assets/91766951/41706c97-9983-4ed2-b6ca-725ee520cc70)

**Comment by troyeguo** [comment]
感谢您的反馈，会在下个版本修复的

**Comment by troyeguo** [comment]
请升级1.6.0版
