### ISSUE TITLE
书架添加图书的BUG、以及一些优化建议【已解决】

### ISSUE THREAD

**Issue by jkqxl** [koodo-reader/koodo-reader#981]
### 我已经从 Github Release 安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10 及以下

### Koodo Reader 版本

开发版 1.5.9

### 我遇到的问题

目前的添加图书流程是：
某些类别的图书 --->全部图书界面 --->右键多选--->全选--->添加到书架
重复。。。。。。

问题：在批量添加 TXT图书时发现，明明是分批次添加的，但最终在不想要的书架中也出现了，例如，实际是将书移动到书架1 ，但结果是书架2中也有。删除重复添加，结果也一样，而且一本本的检索，基本没办法。

流程优化：创建新的书架1、2、3......，再在对应书架添加书籍就好，而不是需要先添加，再移动。并且在删除书架时，希望可以只是清空图书，而不是删除书架本身。

**Comment by troyeguo** [comment]
可以先切换到书架，然后再导入图书，图书会自动加入当前书架。我这边无法复现您提到的重复添加的问题，您可提供一下屏幕录像吗

**Comment by jkqxl** [comment]
> 可以先切换到书架，然后再导入图书，图书会自动加入当前书架。我这边无法复现您提到的重复添加的问题，您可提供一下屏幕录像吗

问题是想要添加修改新的书架名称，而现在却没有这个功能，只能重新添加移动

**Comment by troyeguo** [comment]
感谢您的反馈，会在下个版本修复这个问题，会考虑您的建议的

**Comment by jkqxl** [comment]
> 感谢您的反馈，会在下个版本修复这个问题，会考虑您的建议的

有用就好。。。
