### ISSUE TITLE
docker 部署出错

### ISSUE THREAD

**Issue by xinmans** [koodo-reader/koodo-reader#985]
### I've already installed the latest developer version of Koodo Reader from Github Release, this problem still exsits

- [X] Yes

### There are no similar issues on the issue list

- [X] Yes

### I've already read the document, still can't solve it.

- [X] Yes

### Operating system or browser

Ubuntu

### App Version

1.6.0

### Bug Detail

sudo docker-compose up -d --build
[+] Building 3.5s (10/12)                                                                                                                                                                            docker:default
 => [koodo internal] load build definition from Dockerfile                                                                                                                                                     0.3s
 => => transferring dockerfile: 32B                                                                                                                                                                            0.0s
 => [koodo internal] load .dockerignore                                                                                                                                                                        0.1s
 => => transferring context: 2B                                                                                                                                                                                0.0s
 => [koodo internal] load metadata for docker.io/library/caddy:latest                                                                                                                                          0.8s
 => [koodo internal] load metadata for docker.io/library/node:14-slim                                                                                                                                          0.8s
 => [koodo builder 1/6] FROM docker.io/library/node:14-slim@sha256:198142146b4c47193348f6415da769bdb5035c16fcab051c38c256a6b48f2e1c                                                                            0.0s
 => CACHED [koodo stage-1 1/2] FROM docker.io/library/caddy:latest@sha256:325f81ca0328db0737503a53f43717fce79ea0c574e83f8e586c8d350cadf34b                                                                     0.0s
 => CACHED [koodo builder 2/6] RUN apt-get update && apt-get install -y jq curl wget python                                                                                                                    0.0s
 => CACHED [koodo builder 3/6] WORKDIR /app                                                                                                                                                                    0.0s
 => CACHED [koodo builder 4/6] RUN tarball_url=$(curl -s https://api.github.com/repos/troyeguo/koodo-reader/releases/latest | jq -r ".tarball_url")     && wget -qO- $tarball_url     | tar xvfz - --strip 1   0.0s
 => ERROR [koodo builder 5/6] RUN yarn --network-timeout 1000000                                                                                                                                               2.3s
------
 > [koodo builder 5/6] RUN yarn --network-timeout 1000000:
1.353 yarn install v1.22.19
1.829 [1/5] Validating package.json...
1.842 error koodo-reader@1.5.9: The engine "node" is incompatible with this module. Expected version "18.x". Got "14.21.3"
1.867 error Found incompatible module.
1.869 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
------
failed to solve: executor failed running [/bin/sh -c yarn --network-timeout 1000000]: exit code: 1

**Comment by troyeguo** [comment]
已修复
