### ISSUE TITLE
1.5.9文本高亮没有效果

### ISSUE THREAD

**Issue by huluxia** [koodo-reader/koodo-reader#986]
### I've already installed the latest developer version of Koodo Reader from Github Release, this problem still exsits

- [X] Yes

### There are no similar issues on the issue list

- [X] Yes

### I've already read the document, still can't solve it.

- [X] Yes

### Operating system or browser

Windows 10 and below

### App Version

1.5.9

### Bug Detail

1.5.9文本高亮没有效果

### Screenshots (Optional)

![image](https://github.com/troyeguo/koodo-reader/assets/18514186/84672d63-b9d8-407e-9c8e-bbbdb84af3b9)

**Comment by huluxia** [comment]
标记的时候没有马上出现效果，必须翻页到别的页面再回来才看到高亮

**Comment by huluxia** [comment]
Bug多高亮，现在添加高亮，怎么都不显示

**Comment by troyeguo** [comment]
麻烦提供一下电子书文件

**Comment by huluxia** [comment]
[Uploading 股票大作手操盘术_融合时间和价格的利弗莫尔准则.zip…]()

**Comment by troyeguo** [comment]
> Uploading 股票大作手操盘术_融合时间和价格的利弗莫尔准则.zip…

您的电子书文件没有上传成功，请等待上传完成

**Comment by huluxia** [comment]
不止一本书，很多书高亮都有问题

**Comment by huluxia** [comment]
[股票大作手操盘术_融合时间和价格的利弗莫尔准则.zip](https://github.com/koodo-reader/koodo-reader/files/13258172/_.zip)

**Comment by troyeguo** [comment]
感谢您的反馈，会在下个版本修复的

**Comment by huluxia** [comment]
谢谢您

**Comment by troyeguo** [comment]
请升级1.6.0版

**Comment by huluxia** [comment]
您好！1.6.0版本依然高亮有问题，我回退到1.5.7版本这个版本，发现高亮都没有问题。

**Comment by huluxia** [comment]
1.5.6高亮暂时应该是bug最少的。后面的版本高亮多多少少都有问题

**Comment by troyeguo** [comment]
请问网页版存在这个问题吗？
https://reader.960960.xyz/#/manager/home

我这里1.6.0没法复现这个问题
![image](https://github.com/koodo-reader/koodo-reader/assets/13820674/a3fb1efa-f27e-4e6f-a637-c6f54c0b3873)

**Comment by huluxia** [comment]
刚试了网页版，高亮的时候并不能马上高亮，要翻页回来才看到高亮。
