### ISSUE TITLE
1.6相比1.5.7退步不少。双屏中间线没了，章节名称字变小了，鼠标滑动一次跑好几页。

### ISSUE THREAD

**Issue by theking988** [koodo-reader/koodo-reader#988]
### 我已经从 Github Release 安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

macOS 12

### Koodo Reader 版本

1.6

### 我遇到的问题

1，自带背景那几项都有中间竖条（双页模式），但是在自定义颜色背景的页面，中间的竖条没有了。
2，章节的名称字变小了。很怪异。
3，鼠标上下滚动。以前一次滑动多少都是一页。现在只能一点点动。稍多一点就跑2，3页。使用起来非常不方便。

其实1.5.7. 算很不错的版本了。只要修改一下性能就好了。唯一发现的BUG是在读比较大的txt小说中，阅读一段时间后，上下页切换会卡几秒。其实没发现问题。

**Comment by troyeguo** [comment]
感谢您的反馈,会考虑的

**Comment by thinkfan** [comment]
@troyeguo  试用了下 1.6，导航还是有点问题：图片引用下划线可以导航到图片，但是回去不能导航，导航最好能“有去有回”，脚注还是不能导航。

楼主说的双屏中间线，我这边更改默认背景色后，是有的（如下图），不过我是win10系统。字体大小我自己重新设置了下，感觉还行。翻页我一般用上下左右箭头，也还行。之前1.5.9有问题的时候，我也是退回到1.5.7，哈哈。

![2023-11-06_080210](https://github.com/koodo-reader/koodo-reader/assets/1967862/c7e873fb-94e8-4e30-9fb5-a9298378da73)

**Comment by theking988** [comment]
默认背景是有用的。我说的没有分隔线是自定义颜色背景。因为默认的绿色太绿了。不适合看小说。所以我都是自定义。
![Uploading WX20231106-101652@2x.png…]()
