### ISSUE TITLE
1.6的markdown  文件还是不能浏览

### ISSUE THREAD

**Issue by LuckyHangMei** [koodo-reader/koodo-reader#989]
### I've already installed the latest developer version of Koodo Reader from Github Release, this problem still exsits

- [X] Yes

### There are no similar issues on the issue list

- [X] Yes

### I've already read the document, still can't solve it.

- [X] Yes

### Operating system or browser

Windows 10 and below

### App Version

1.6.0

### Bug Detail

![image](https://github.com/koodo-reader/koodo-reader/assets/64392435/7d0a54f1-faad-4b35-a40e-28a3f72a5efe)

**Comment by troyeguo** [comment]
麻烦提供一下markdown文件
