### ISSUE TITLE
会有莫名其妙的高亮标记

### ISSUE THREAD

**Issue by MUGGLEYUAN** [koodo-reader/koodo-reader#990]
### 我已经从 Github Release 安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 11

### Koodo Reader 版本

1.5.1

### 我遇到的问题

经常使用高亮标记段落，但其他文字有时也会出现高亮标记。

### 截图或录像(可选的)

![image](https://github.com/koodo-reader/koodo-reader/assets/149987514/072ad346-3eab-47e8-a118-5443e18b76fb)

**Comment by jjxyai** [comment]
借楼，还有是英文的高亮不显示的问题，15.9和1.6.0版本的都有。
![image](https://github.com/koodo-reader/koodo-reader/assets/17805770/5bccce28-6a2d-46d7-8c90-2531070b625c)

**Comment by troyeguo** [comment]
> 借楼，还有是英文的高亮不显示的问题，15.9和1.6.0版本的都有。 ![image](https://user-images.githubusercontent.com/17805770/282501064-5bccce28-6a2d-46d7-8c90-2531070b625c.png)

麻烦提供一下电子书文件

**Comment by zhou-jiale2000** [comment]
实测使用15.7/15.9/16.0都能复现这个问题，操作系统为windows11
问题描述：高亮显示位置漂移到后一页，无法正常删除
复现方式：在同一个段落高亮多个词汇，往后翻几页，翻回来，重复多次
关闭应用再次打开，问题仍然存在。

**Comment by troyeguo** [comment]
> 实测使用15.7/15.9/16.0都能复现这个问题，操作系统为windows11 问题描述：高亮显示位置漂移到后一页，无法正常删除 复现方式：在同一个段落高亮多个词汇，往后翻几页，翻回来，重复多次 关闭应用再次打开，问题仍然存在。

我这里无法复现，您方便录一下操作视频吗？
