### ISSUE TITLE
txt文件章节名重复时，会导致软件卡顿和章节内容空白

### ISSUE THREAD

**Issue by daluan2000** [koodo-reader/koodo-reader#991]
### 我已经从 Github Release 安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 11

### Koodo Reader 版本

1.5.1

### 我遇到的问题

比如在某个txt文件中，第一章的章节名和章节编号在连续的两行中重复出现，然后紧随的是章节内容：
> 第一章 章节名xxx
> 第一章 章节名xxx
> 章节内容xxxxxxx...

这种情况下会导致软件卡顿和章节内容空白

**Comment by iibrat** [comment]
好多大一点的电子书快速翻页都会卡顿
