### ISSUE TITLE
UI方面的小建议

### ISSUE THREAD

**Issue by GeekLee2012** [koodo-reader/koodo-reader#993]
### 我已经阅读了 Koodo Reader 的开发计划，没有找到类似的需求

- [X] Yes

### 这个 issue 没有同时提多个需求.

- [X] Yes

### 简单介绍

作者你好！
我在macOS下简单体验了下Koodo Reader。
UI方面感受如下：
1、封面图片太小，显得不够大方；
2、文字标题、描述等元素，颜色一样、深浅度一样，不够分明；
3、UI元素不统一，有的圆角、有的直角；

建议：
1、封面图片调大，这样大方清晰，且更易于操作；
2、文字标题、描述等调整颜色、深浅度、大小等，增大区别，这样更清晰、分明；
3、UI统一方面，暂时没有具体建议；

下面图片为我下载源码，简单修改后打包的本地版本，
由于对源码不熟悉，修改代码有点入侵性、破坏性未知，哈哈。

### 细节描述

<img width="1217" alt="Screen Shot 2023-11-14 at 17 46 20" src="https://github.com/koodo-reader/koodo-reader/assets/14144549/32511f6a-0536-4c81-ac34-980a6ab87080">
<img width="1194" alt="Screen Shot 2023-11-14 at 17 46 50" src="https://github.com/koodo-reader/koodo-reader/assets/14144549/8bffbccb-329c-4f0a-8fb9-93d6e2d3c6bb">
<img width="1196" alt="Screen Shot 2023-11-14 at 17 46 28" src="https://github.com/koodo-reader/koodo-reader/assets/14144549/fa9a9d4c-883b-4e7b-9ac4-6c3b9fdd702c">
<img width="1193" alt="Screen Shot 2023-11-14 at 17 47 18" src="https://github.com/koodo-reader/koodo-reader/assets/14144549/28e278fb-9c9b-4aaa-b7b9-148b90f50a27">

**Comment by troyeguo** [comment]
后续会支持自定义封面大小的，现在可以切换封面模式
![image](https://github.com/koodo-reader/koodo-reader/assets/13820674/10346acf-fa45-44f6-8006-72810a400278)

**Comment by GeekLee2012** [comment]
好的！谢谢回复！这个模式其实我也知道的。

只是这个模式下，很多书籍的信息一般不太完整，
就会容易出现太多重复，且无实际意义的文字信息，
如上图，出版商、描述、这里什么都没有等等这些文字，
当信息不完整时，这些就显得无意义。
对浏览体验也造成一定的干扰，
不如第一、第二种浏览模式的清晰简洁。

但目前第一、第二种浏览模式，
封面图片在电脑客户端下稍微显得小些，
且标题文字看起来不够清晰分明。
一般，只要封面够大，就可以不用看标题，也能很容易找到想看的书籍。
极端情况下，若有两本书封面相似度很高，大封面下也能做到更容易区分。

图片大小、文字大小、颜色、间距（行间距、字间距、上下左右间距）等等，
这些都是对浏览体验、操作体验有非常直接影响的要素。

题外话，我在macOS主要用Koodo看mobi格式电子书，
epub、pdf还是在使用系统自带的，
毕竟系统自带的阅读体验更好，
Koodo在这方面还有很长一段路要追赶。

最后，期待和祝愿Koodo Reader越来越好！加油！
